'use strict';
/**
 * agent.js — OYE as a reasoning agent. A language model (Claude through the page, Ollama, or any open model
 * endpoint) thinks step by step and acts through tools that expose everything OYE knows and can do: its memory,
 * the trips and seats, the written policies, the destinations table, the risk desk, the council of agents, the lead
 * sheet, holds, campaigns and content. Every run ends with facts the mind memorises, so the agent learns from use,
 * and every answer can be corrected by the chief, which becomes a lesson for the next time.
 *
 * Without a model the agent still works: it routes the request to the closest tool by keywords. Nothing breaks offline.
 */
const DEST = require('./destinations');

const MAX_STEPS = 8;

function tools(brain) {
  const g = brain.growth; const m = brain.memory;
  const T = {
    recall: { desc: 'Search what OYE remembers (facts, lessons, policies, people). args: {query}', run: async ({ query }) => { const r = await brain.respond(String(query || ''), { user: 'agent' }); const facts = m.recall(String(query || ''), 8).map(f => f.text || `${f.s} ${f.p} ${f.o}`); return { answer: r.text, facts }; } },
    trips: { desc: 'Upcoming trips with date, price, seats left, holds. args: {}', run: async () => g.upcoming(10).map(t => ({ name: t.name, date: t.date, days: t.days, price: t.price, seats: t.seats, booked: t.booked, seatsLeft: g.seatsLeft(t), holds: (t.holds || []).length })) },
    policies: { desc: 'The written policies (included, excluded, payment, cancellation, pickup, safety, food, age) and business profile. args: {}', run: async () => ({ business: { name: g.profile.name, city: g.profile.city, phone: g.profile.phone, upi: g.profile.upi, usp: g.profile.usp }, policies: g.profile.policies }) },
    destination: { desc: 'Facts about a destination: season months, min/ideal days, cost per day, altitude, permits, risks, route. args: {name}', run: async ({ name }) => { const d = DEST.find(String(name || '')); return d ? { ...d, now: DEST.seasonStatus(d, new Date().getMonth() + 1) } : { error: 'unknown destination; known: ' + Object.values(DEST.DESTINATIONS).map(x => x.name).join(', ') }; } },
    plan_trip: { desc: 'Operations + critic build a day-by-day plan with price and findings from one line of requirements. args: {requirements}', run: async ({ requirements }) => { const r = await brain.council.review({ message: String(requirements || '') }); const o = r.agents.operations && r.agents.operations.output || {}; return { verdict: r.verdict, season: o.season, perPerson: o.perPerson, itinerary: (o.itinerary || []).map(d => `D${d.day} ${d.plan}`), findings: [].concat(...Object.values(r.agents).map(a => a.findings || [])).slice(0, 8), fixes: r.fixes.slice(0, 6) }; } },
    analyse_lead: { desc: 'Full council pass on a customer conversation: cohort, stage, lead score, next action, draft reply, issues. args: {conversation, name?}', run: async ({ conversation, name }) => { const r = await brain.council.handle({ conversation: String(conversation || ''), name: name || '' }); const s = r.agents.sales && r.agents.sales.output || {}; return { verdict: r.verdict, cohort: s.cohort, stage: s.stage, score: s.score, nextAction: s.nextAction, draft: s.draft, issues: [].concat(...Object.values(r.agents).map(a => a.findings || [])).slice(0, 6) }; } },
    whatsapp_reply: { desc: 'What the WhatsApp agent would reply to a customer message, grounded on real trips and policies (EN/Hinglish/Gujarati/Hindi). args: {text, id?}', run: async ({ text, id }) => { const r = await g.chat({ id: id || 'agent-' + Date.now().toString(36), text: String(text || ''), source: 'agent' }); return { reply: r.reply, intent: r.intent, handoff: r.handoff, stage: r.stage }; } },
    leads: { desc: 'The lead sheet; optional stage filter. args: {stage?}', run: async ({ stage }) => g.state.leads.filter(l => !stage || l.stage === stage).slice(0, 50).map(l => ({ id: l.id, name: l.name, trip: l.trip, stage: l.stage, source: l.source, touches: l.touches, next: new Date(l.next).toISOString().slice(0, 10), value: l.value })) },
    today: { desc: 'Follow-ups due now with drafted messages, seat alerts, pipeline counts. args: {}', run: async () => { const t = await g.today(); return { due: t.due.map(d => ({ lead: d.lead.name || d.lead.id, trip: d.lead.trip, stage: d.lead.stage, step: d.step.name, message: d.message })), alerts: t.alerts, counts: t.counts }; } },
    add_lead: { desc: 'Add or update a lead. args: {name, phone?, trip?, stage?, source?, value?, notes?}', run: async (a) => g.addLead(a || {}) },
    hold_seats: { desc: 'Hold seats on a trip for a lead for 24h. args: {trip, lead, n}', run: async ({ trip, lead, n }) => { const t = g.profile.trips.find(x => x.name.toLowerCase().includes(String(trip || '').toLowerCase())); if (!t) return { error: 'no such trip' }; const h = g.hold(t, String(lead || 'agent'), +n || 1); return { held: h.n, trip: t.name, until: new Date(h.until).toISOString(), seatsLeft: g.seatsLeft(t) }; } },
    campaigns: { desc: 'Festival/season campaign calendar with start dates, and broadcast drafts per segment. args: {}', run: async () => ({ campaigns: g.campaigns(), broadcasts: (await g.broadcasts()).drafts }) },
    content: { desc: 'Instagram bio, 7-day post plan with scripts and captions, hashtags; Google posts and keywords. args: {}', run: async () => { const c = await g.content(); const posts = await g.gbpPosts(); return { bio: c.bio, week: c.plan.map(p => `${p.day} ${p.format}: ${p.idea}`), captions: c.plan.filter(p => p.caption).map(p => p.caption), hashtags: c.hashtags, googlePosts: posts.map(p => p.title + ' — ' + p.body), keywords: g.keywords() }; } },
    risk: { desc: 'Travel risks and news affecting a place. args: {place}', run: async ({ place }) => brain.risk.relevant(String(place || ''), '').slice(0, 8) },
    calc: { desc: 'Arithmetic. args: {expression} e.g. "4*14500*0.3"', run: async ({ expression }) => { const e = String(expression || '').replace(/[^0-9+\-*/().% ]/g, ''); try { return { result: Function('"use strict";return (' + e + ')')() }; } catch (x) { return { error: 'bad expression' }; } } },
    remember: { desc: 'Memorise durable facts (plain sentences, one per item). args: {facts: [..]}', run: async ({ facts }) => ({ learned: brain.teach((facts || []).join('\n'), { source: 'agent', importance: 0.8 }) }) },
    persona: { desc: 'Read a customer message and return the psyche cues that matter (anxious, skeptical, analytical, consensus seeker, price sensitive, wants it all handled, rushed, terse, family) with handling advice. args: {text}', run: async ({ text }) => { const U = require('./universe'); const traits = U.detect(String(text || '')); const TIPS = { anxious: 'lead with safety proof before price', skeptical: 'offer reviews, last batch photos and a past traveller to call', analytical: 'send the inclusions list and the day-wise plan before asking for a hold', 'consensus seeker': 'give a forwardable one-page plan and a 24h hold without advance', 'defers to spouse or parent': 'write the message so it can be forwarded as is', 'very price sensitive': 'show the all-inclusive comparison and pay-in-parts', 'wants it all handled': 'promise pickup to drop in one sentence', rushed: 'answer in two lines and offer the hold now', terse: 'reply under 40 words', 'family with kids': 'answer safety, food and pace first', 'family with seniors': 'answer altitude, walking and doctor first' }; return { traits, advice: traits.map(t => TIPS[t]).filter(Boolean) }; } },
    activities: { desc: 'Things to do at a destination with start times, durations, costs, best months, who it suits. args: {name}', run: async ({ name }) => { const d = DEST.find(String(name || '')); return d ? { destination: d.name, activities: DEST.activitiesFor(d.name) } : { error: 'unknown destination' }; } },
    brief_5w1h: { desc: 'Why, who, where, what, when, whom, which, how for a destination. args: {name, month?, days?, n?, budget?}', run: async ({ name, month, days, n, budget }) => { const S = require('./strategy'); const d = DEST.find(String(name || '')); return d ? S.fiveW(d, { month: DEST.monthNum(month) || +month || null, days, n, budget, activities: DEST.activitiesFor(d.name) }) : { error: 'unknown destination' }; } },
    personality: { desc: 'Personality read of a message: Big Five, MBTI, DISC, Enneagram, generation, archetype, attachment, money style, with handling advice. args: {text}', run: async ({ text }) => require('./minds').brief(String(text || '')) },
    therapy: { desc: 'Travel as therapy: trip, pace, group and actions for a state of mind (burnout, grief, heartbreak, anxiety, loneliness, low confidence, creative block, family distance, couple strain, retirement). args: {state}', run: async ({ state }) => { const M = require('./minds'); const k = Object.keys(M.THERAPY).find(x => String(state || '').toLowerCase().includes(x)) || M.detectAll(String(state || '')).therapy[0]; return k ? { state: k, ...M.THERAPY[k], note: 'Travel helps; it is not treatment.' } : { options: Object.keys(M.THERAPY) }; } },
    strategy: { desc: 'Business techniques for a situation (no leads, low conversion, cancellations, low fill, low margin, bad reviews, seasonality, competition, cash flow, growth). args: {situation}', run: async ({ situation }) => require('./strategy').techniques(String(situation || '')) },
    pricing_strategy: { desc: 'Price ladder and rules. args: {cost?, price?, competitor?, seats?, booked?, daysOut?}', run: async (a) => require('./strategy').priceStrategy(a || {}) },
    pricing_analytics: { desc: 'Per-trip price per day vs ground benchmark, implied margin, fill, quote-to-book, revenue, with notes. args: {}', run: async () => require('./strategy').priceAnalytics(g.upcoming(10), g.state.leads, DEST) },
    patterns: { desc: 'Patterns in the lead sheet and chat log: hours, days, sources, funnel, demand, touches to book. args: {}', run: async () => require('./strategy').patterns(g.state.leads, g.state.log) },
    read_news: { desc: 'Read pasted headlines or an article: affected destinations, severity, topic, action; logs risks. args: {text}', run: async ({ text }) => require('./strategy').readNews(String(text || ''), DEST, brain.risk) },
    understand: { desc: 'Ultimate understanding of one customer message: intent, emotion, requirements, psyche, personality, therapy cues, the one right move. args: {text}', run: async ({ text }) => { const r = brain.skills.tryAll('understand: ' + String(text || '')); return r ? { understanding: r.output } : { error: 'no read' }; } },
    review_reply: { desc: 'Draft a reply to a Google review. args: {text, stars, name?}', run: async ({ text, stars, name }) => g.reviewReply(String(text || ''), +stars || 5, name || '') },
  };
  return T;
}

const SYSTEM = (names) => `You are OYE, the operating mind of Travelers Clan, an Indian group-travel company. You think step by step and act through tools. You never invent prices, dates, seats or policies: fetch them with tools. Be concrete, short, and commercially sharp. Money in INR.
Protocol: reply with JSON only. Either {"thought": "...", "tool": "<name>", "args": {...}} to use a tool, or {"thought": "...", "final": "<answer for the chief, plain text, may be multi-line>", "facts": ["durable fact to memorise", ...], "todo": ["one next action for the chief", ...]} when done.
Tools: ${names}. Use at most ${MAX_STEPS} tool calls. Prefer trips/policies/today before answering anything about the business. If the request is a message to a customer, produce the exact text to send.`;

class Agent {
  constructor(brain) { this.brain = brain; this.tools = tools(brain); this.log = []; }
  get llm() { const m = this.brain.mentor; return m && m.enabled ? m : null; }

  async run(request, { maxSteps = MAX_STEPS } = {}) {
    const started = Date.now(); const steps = []; const names = Object.entries(this.tools).map(([k, t]) => `${k}: ${t.desc}`).join('\n');
    const llm = this.llm;
    let final = null, facts = [], todo = [];
    if (llm) {
      let transcript = `Request from the chief: ${request}`;
      for (let i = 0; i < maxSteps + 1; i++) {
        const out = await llm.json(SYSTEM(names), transcript + (i >= maxSteps ? '\n\nYou are out of tool calls: answer now with "final".' : ''), { maxTokens: 900 });
        if (!out) { final = null; break; }
        if (out.final) { final = String(out.final); facts = Array.isArray(out.facts) ? out.facts.filter(f => typeof f === 'string' && f.length > 8).slice(0, 5) : []; todo = Array.isArray(out.todo) ? out.todo.slice(0, 5) : []; break; }
        const tool = this.tools[out.tool];
        if (!tool) { transcript += `\n\nStep ${i + 1}: unknown tool "${out.tool}". Available: ${Object.keys(this.tools).join(', ')}.`; continue; }
        let result; try { result = await tool.run(out.args || {}); } catch (e) { result = { error: e.message }; }
        const short = JSON.stringify(result).slice(0, 2500);
        steps.push({ thought: out.thought, tool: out.tool, args: out.args || {}, result: JSON.parse(JSON.stringify(result, (k, v) => typeof v === 'string' && v.length > 600 ? v.slice(0, 600) + '…' : v)) });
        transcript += `\n\nStep ${i + 1}: thought: ${out.thought || ''}\ntool ${out.tool}(${JSON.stringify(out.args || {})}) → ${short}`;
      }
    }
    if (final == null) { const r = await this.fallback(request); final = r.final; steps.push(...r.steps); }
    if (facts.length) this.brain.teach(facts.join('\n'), { source: 'agent', importance: 0.8 });
    const entry = { id: Date.now().toString(36) + Math.random().toString(36).slice(2, 5), t: started, request, final, steps, facts, todo, ms: Date.now() - started, model: llm ? llm.status().model : 'rules only' };
    this.log.push(entry); if (this.log.length > 200) this.log.splice(0, this.log.length - 200);
    this.brain.event('agent', `${request.slice(0, 60)} → ${steps.length} step(s), ${facts.length} fact(s), ${entry.ms}ms`);
    return entry;
  }

  /** No model: answer the specific thing asked from the tools, then present it plainly. */
  async fallback(request) {
    const r = String(request).toLowerCase(); const steps = []; const g = this.brain.growth; const P = g.profile;
    const use = async (name, args) => { const result = await this.tools[name].run(args); steps.push({ tool: name, args, result }); return result; };
    const money = (n) => '₹' + Math.round(+n || 0).toLocaleString('en-IN'); const fmtDate = (d) => new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
    const tripNamed = () => g.upcoming(10).find(t => r.includes(t.name.toLowerCase())) || null;
    const n = +(r.match(/\b(\d{1,2})\s*(?:people|pax|persons|of us|friends|members|log|logon|guys|ppl)\b|\bfor\s+(\d{1,2})\b/) || []).slice(1).find(Boolean) || 0;
    const monthIdx = DEST.monthNum((r.match(/\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b/) || [])[1]);
    let final;
    const policyKey = /\b(cancel|refund)/.test(r) ? 'cancellation' : /\b(include\w*|inclusion\w*|covered|what do (i|we) get)\b/.test(r) && !/not included|exclu/.test(r) ? 'included' : /\b(not included|exclu|extra)\b/.test(r) ? 'excluded' : /\b(pickup|boarding|start point)\b/.test(r) ? 'pickup' : /\b(safe|safety|women|girls)\b/.test(r) ? 'safety' : /\b(veg|food|jain|meal)\b/.test(r) ? 'food' : /\b(kids?|children|age|senior|parents)\b/.test(r) && /\b(allow|ok|policy|rule|suitable)\b/.test(r) ? 'age' : /\b(review|proof|genuine)\b/.test(r) ? 'proof' : /\b(payment|pay|instal|gst|invoice)\b/.test(r) && !/advance/.test(r) ? 'payment' : null;
    if (/\badvance\b/.test(r) && (tripNamed() || g.upcoming(1)[0])) { const t = tripNamed() || g.upcoming(1)[0]; const adv = g.advance(t); await use('trips', {}); final = `Advance for ${t.name}: ${money(adv)} per person${n ? `, ${money(adv * n)} for ${n}` : ''}. Balance ${money(t.price - adv)} per person${n ? ` (${money((t.price - adv) * n)} total)` : ''} is due 7 days before departure${P.upi ? '. UPI: ' + P.upi : ''}.`; }
    else if (/^\s*(news|headlines?)\s*[:\-]/i.test(request) || /\b(read (this|the) news|what does this news mean|news:)\b/i.test(r)) { const n = await use('read_news', { text: request.replace(/^\s*(news|headlines?)\s*[:\-]\s*/i, '') }); final = n.summary + '\n' + n.items.map(i => `• [${i.severity}] ${i.destination || 'general'} · ${i.topic}: ${i.headline}\n  → ${i.action}`).join('\n'); }
    else if (/\b(pattern|patterns|trend|trends|insight|what do the leads show|analy[sz]e (the )?leads)\b/.test(r)) { const p = await use('patterns', {}); final = p.findings.map(f => '• ' + f).join('\n') + (p.leadsBySource.length ? '\nSources: ' + p.leadsBySource.map(([s, n]) => `${s} ${n}`).join(', ') : ''); }
    else if (/\b(pricing analytics|price analytics|margin per trip|are we priced|price per day|pricing review)\b/.test(r)) { const a = await use('pricing_analytics', {}); final = a.rows.map(x => `${x.trip}: ${money(x.price)} (${money(x.perDay)}/day vs ground ${x.benchmarkCostPerDay ? money(x.benchmarkCostPerDay) : '?'}, margin ${x.impliedMargin == null ? '?' : x.impliedMargin + '%'}), ${x.fill}% full, ${x.leads} leads → ${x.booked} booked${x.quoteToBook != null ? ' (' + x.quoteToBook + '%)' : ''}`).join('\n') + (a.notes.length ? '\n' + a.notes.map(n => '• ' + n).join('\n') : '\n• Nothing out of line.'); }
    else if (/\b(pricing strategy|price ladder|how (should|do) (we|i) price|early bird)\b/.test(r)) { const t = tripNamed() || g.upcoming(1)[0]; const d = t ? DEST.find(t.name) : null; const ps = await use('pricing_strategy', { price: t ? t.price : null, cost: d && t ? d.costPerDay * (t.days || d.idealDays) : null, seats: t ? t.seats : null, booked: t ? t.booked : 0, daysOut: t && t.date ? Math.ceil((new Date(t.date) - Date.now()) / 864e5) : 45, competitor: +(r.match(/competitor\s*(?:at|rs\.?|₹)?\s*([\d,]{4,})/) || ['', '0'])[1].replace(/,/g, '') || null }); final = (t ? `${t.name}: standard ${money(ps.base)}, ${ps.fill}% full, ${ps.left} left.\n` : '') + ps.ladder.map(l => `• ${l.tier}: ${money(l.price)} — ${l.why}`).join('\n') + '\nRules:\n' + ps.rules.map(x => '• ' + x).join('\n'); }
    else if (/\b(strategy|strategies|technique|playbook|how (do|to) (we|i) (fix|grow|handle|improve|increase|reduce)|what should we do about)\b/.test(r) && !/price ladder|pricing strategy/.test(r)) { const st = await use('strategy', { situation: request }); final = st.map(x => `${x.situation.toUpperCase()}:\n` + x.moves.map(([n, d]) => `• ${n}: ${d}`).join('\n')).join('\n\n'); }
    else if (/\b(things to do|what to do|activities|activity timings?)\b/.test(r) && DEST.find(r)) { const a = await use('activities', { name: DEST.find(r).name }); final = `Things to do in ${a.destination}:\n` + (a.activities.length ? a.activities.map(x => `• ${x.name} — ${x.start}, ${x.hours} h, ${x.cost ? money(x.cost) : 'free'}, best ${x.best}, for ${x.who}`).join('\n') : 'see the route in the brief'); }
    else if (/\b(brief|everything about|tell me (all )?about|overview|why who|5w)\b/.test(r) && DEST.find(r)) { const w = await use('brief_5w1h', { name: DEST.find(r).name, month: (r.match(/\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b/) || [])[1], n: +(r.match(/\b(\d{1,2})\s*(?:people|pax|of us)\b/) || [])[1] || null }); final = ['WHAT: ' + w.what, 'WHY: ' + w.why, 'WHO: ' + w.who, 'WHERE: ' + w.where, 'WHEN: ' + w.when, 'WHOM: ' + w.whom, 'WHICH: ' + w.which, 'HOW: ' + w.how].join('\n'); }
    else if (/\b(therapy|heal|healing|burn ?out|grief|heartbreak|break ?up|lonely|loneliness|confidence|creative block|reconnect|rekindle)\b/.test(r)) { const t = await use('therapy', { state: request }); final = t.state ? `${t.state}: needs ${t.needs}.\nTrip: ${t.trip}. Pace: ${t.pace}. Group: ${t.group}.\nDo: ${t.do.join('; ')}.\nAvoid: ${t.avoid}.\n${t.note}` : 'States I can match: ' + t.options.join(', '); }
    else if (/^\s*(understand|analy[sz]e|decode|read deeply|personality|profile)\s*[:\-]/i.test(request)) { const isP = /^\s*(personality|profile)/i.test(request); const text = request.replace(/^\s*\w+(\s+\w+)?\s*[:\-]\s*/, ''); if (isP) { const b = await use('personality', { text }); final = b.lines.length ? b.lines.map(l => '• ' + l).join('\n') : 'No strong cue; ask one open question.'; } else { const u = await use('understand', { text }); final = u.understanding || u.error; } }
    else if (/\b(broke down|breakdown|accident|stuck|landslide|medical emergency|hospital|missing|lost (a |one )?(traveller|passenger|person)|stranded|fight|drunk|police|snowed in|road (closed|blocked)|flight cancelled)\b/.test(r)) {
      const SOP = [['broke down|breakdown|stuck|stranded', ['Captain keeps everyone on or near the vehicle, counts heads, shares live location in the trip group.', 'Captain calls the backup vehicle contact for that route (every route has one) and the founder; ETA posted to the group within 10 minutes.', 'Water, snacks and blankets from the trip kit; nobody walks off in the dark.', 'If the wait exceeds 90 minutes, book the nearest safe stop (dhaba or hotel) and bill it to the company.', 'Message every traveller\'s emergency contact only if the delay crosses 3 hours.', 'Next morning: a voice note from the founder to the group, a small gesture (meal or activity on us), and a note in the incident log.']],
        ['accident|medical|hospital', ['Captain calls 112 and the nearest hospital from the route sheet; one captain stays with the injured, the other with the group.', 'Founder informed immediately; founder calls the emergency contact.', 'Insurance and ID copies from the booking file sent to the hospital.', 'No statements to anyone outside the company; the founder handles communication.']],
        ['missing|lost', ['Last seen time and place from the group; captain retraces with one volunteer while the group stays put.', 'Call the traveller, then the emergency contact; after 30 minutes inform local police with a photo from the booking file.', 'Founder on the phone until found.']],
        ['landslide|road (closed|blocked)|snowed|flight cancelled', ['Stop at the nearest safe town; captain books rooms, company pays.', 'Rework the plan with the ground partner; tell the group one clear new plan within an hour, not a running commentary.', 'Advance stays fully transferable for anyone who wants out; refunds for skipped paid activities.']],
        ['fight|drunk|police', ['Captain separates the people involved, no arguments in public; a quiet word each.', 'Zero tolerance policy read out once; a second incident means the traveller leaves the trip at their own cost.', 'Police: cooperate, founder informed, no one argues with the police.']]];
      const steps = (SOP.find(([re]) => new RegExp(re).test(r)) || SOP[0])[1]; final = 'Do this now, in order:\n' + steps.map((x, i) => `${i + 1}. ${x}`).join('\n'); steps.push(); }
    else if (/\b(push or merge|push|merge|half full|% full|percent full|under ?filled|not filling|cancel the batch)\b/.test(r) && (tripNamed() || /batch|departs/.test(r))) {
      const t = tripNamed() || g.upcoming(1)[0]; const trips = await use('trips', {}); const days = t && t.date ? Math.ceil((new Date(t.date) - Date.now()) / 864e5) : (+(r.match(/in (\d+) days?/) || [])[1] || 0); const fill = t && t.seats ? Math.round(100 * t.booked / t.seats) : (+(r.match(/(\d+)\s*%/) || [])[1] || 0);
      const push = fill >= 40 || days >= 7; final = `${t ? t.name : 'The batch'}: ${fill}% full, ${days} days out. Decision: ${push ? 'PUSH for 48 hours, then decide' : 'MERGE now'}.\n` + (push ? ['1. Today: past-traveller broadcast ("seats open to you first") and a 24-hour hold without advance for warm leads.', '2. Tonight: one reel from the last batch with the seat count on screen; Google post with the same.', '3. Tomorrow: call every quoted lead personally; offer pay-in-parts.', `4. At 48 hours: if under 60% full, merge into the next batch and tell the booked travellers today with a free upgrade (room or activity).`] : ['1. Call every booked traveller today, before any message: move them to the next batch with a free upgrade, or a full refund including advance if the new date does not work.', '2. Cancel the hotel and transport holds now to stop the cost.', '3. Tell warm leads the next date with a 24-hour hold.', '4. Log why it did not fill (date, price, launch too late) so the next batch launches 6 weeks out.']).join('\n'); }
    else if (/\b(campaign|broadcast|diwali|holi|navratri|christmas|new year|festival|promotion)\b/.test(r)) { const c = await use('campaigns', {}); const named = c.campaigns.find(x => r.includes(x.name.split(/[ \/]/)[0].toLowerCase())); final = (named ? `${named.name} (${named.date}), start by ${named.startBy}: ${named.pitch}.\n\nPlan:\n1. Day 1: past-traveller broadcast.\n2. Day 2: warm-lead broadcast and a festival reel with the date and price.\n3. Day 4: organiser offer to colleges, offices and societies.\n4. Day 7: last-call story with seats left.\n\n` : c.campaigns.map(x => `${x.status === 'run now' ? 'RUN NOW' : 'start ' + x.startBy}: ${x.name}, ${x.pitch}`).join('\n') + '\n\n') + 'Messages:\n' + c.broadcasts.map(b => `[${b.segment}] ${b.text}`).join('\n'); }
    else if (/\b(google review|review:|reply to (this|the) review|stars?)\b/.test(r) && /["“'‘]/.test(request)) { const text = (request.match(/["“'‘](.+?)["”'’]/) || [])[1] || request; const stars = +(r.match(/(\d)\s*stars?/) || [])[1] || 5; const w = await use('review_reply', { text, stars }); final = `Reply to post${w.escalate ? ' (call them first)' : ''}:\n${w.reply}`; }
    else if (/\b(what would make|how (do|to|can) (i|we) (convince|win|close|convert)|book with us|convert (a|the)|make .* book)\b/.test(r)) { const pr = await use('persona', { text: request }); const p = await use('policies', {}); final = `Read on them: ${pr.traits.join(', ') || 'no strong cue'}.\n` + (pr.advice.length ? pr.advice.map((a, i) => `${i + 1}. ${a.charAt(0).toUpperCase() + a.slice(1)}.`).join('\n') : '') + `\nProof we give: ${p.policies.proof}\nTrust: advance to the company UPI, GST invoice, written cancellation policy (advance transferable), a past traveller to call.\nClose: a 24-hour hold without advance, then the hold message.`; }
    else if (/\b(zero (ad )?budget|no (ad )?budget|free leads|without ads|organic|no money for ads)\b/.test(r)) { final = ['Leads with zero ad budget, in order of yield:', '1. Google Business Profile: 20 reviews in 30 days, one post a week with the date and price, 10 real photos. Strangers who search "trips from ' + (P.city || 'your city') + '" find you.', '2. One reel a day from real trip footage, faces first, date and price on screen, posted 7 to 9pm.', '3. Organisers: colleges, office HR, housing societies; the organiser travels free for every 10 paid seats. One organiser fills a bus.', '4. Referral: every past traveller gets a personal WhatsApp link; both sides get a discount.', '5. Twenty personal messages a day with a concrete offer ("6 seats left for Goa 12 Dec at ₹14,500, hold two?"), never "please support".', '6. The website trip cards and chat bubble, so every visitor can hold a seat in one tap.'].join('\n'); }
    else if (/\b(lower|reduce|drop|cut|raise|increase|discount)\b/.test(r) && /\b(to|by)\s*(₹|rs\.?)?\s*\d/.test(r) && (tripNamed() || g.upcoming(1)[0])) { const t = tripNamed() || g.upcoming(1)[0]; await use('trips', {}); const m = r.match(/\b(to|by)\s*(?:₹|rs\.?)?\s*(\d[\d,]*)\s*(%|percent)?/); const amt = +m[2].replace(/,/g, ''); const newPrice = m[1] === 'to' ? amt : (m[3] ? Math.round(t.price * (1 - amt / 100)) : t.price - amt); const left = g.seatsLeft(t); const diff = (t.price - newPrice) * left; final = `${t.name}: ${money(t.price)} → ${money(newPrice)} per person. On the ${left} remaining seats that is ${money(Math.abs(diff))} ${diff >= 0 ? 'less' : 'more'} revenue (${money(newPrice * left)} instead of ${money(t.price * left)}). ${diff > 0 ? `It only pays off if the lower price sells at least ${Math.ceil(t.price * left / newPrice) - left} extra seat${Math.ceil(t.price * left / newPrice) - left === 1 ? '' : 's'} you would not have sold otherwise; a hold without advance or pay-in-parts usually moves fence-sitters without cutting the price.` : ''}`; }
    else if (/\b(days? (until|till|to|before|left)|how many days|per day|a day|run ?rate|sell .* per)\b/.test(r) && !/refund|cancel/.test(r) && (tripNamed() || g.upcoming(1)[0])) { const t = tripNamed() || g.upcoming(1)[0]; await use('trips', {}); const days = t.date ? Math.max(0, Math.ceil((new Date(t.date) - Date.now()) / 864e5)) : null; const left = g.seatsLeft(t); final = days == null ? `${t.name} has no date set.` : `${t.name} departs in ${days} days (${t.date}). ${left} seats left: ${days ? (left / days).toFixed(2) : left} seats per day to fill it${days > 14 ? `, or ${(left / Math.max(1, days - 7)).toFixed(2)} per day if you want it full a week early` : ''}. Worth ${money(left * t.price)}.`; }
    else if (/\b(draft|write|compose|make)\b.*\b(message|whatsapp|broadcast|announcement|text)\b/.test(r)) { const t = tripNamed() || g.upcoming(1)[0]; await use('trips', {}); const past = /past|previous|old|earlier|repeat|loyal/.test(r); const left = t ? g.seatsLeft(t) : 0; final = t ? (past ? `Hi {name}, {captain} here from ${P.name}. You travelled with us before, so you hear first: ${t.name}, ${t.date ? fmtDate(t.date) : ''}, ${t.days} days, ${money(t.price)} per person all-inclusive${left ? `, ${left} seats` : ''}. Past travellers get 48 hours before it goes public. Reply YES to hold your seat. Reply STOP to opt out.` : `Hi {name}, ${P.name} here. ${t.name} is confirmed: ${t.date ? fmtDate(t.date) : ''}, ${t.days} days, ${money(t.price)} per person, stay, travel, meals and a trip captain included${left ? `, ${left} seats left` : ''}. Reply PLAN for the day-by-day plan or HOLD to hold a seat. Reply STOP to opt out.`) : 'No trip set up yet.'; final += '\n\nRules: one list per segment, max one broadcast a week, only to people who gave you their number for travel updates.'; }
    else if (/\b(compare|competitor|versus|vs\.?|cheaper)\b/.test(r) && /\d{4,6}|\d{1,3},\d{3}/.test(r)) { const t = tripNamed() || g.upcoming(1)[0]; const p = await use('policies', {}); const other = +(r.match(/(\d{1,3}(?:,\d{3})+|\d{4,6})/) || [])[1].replace(/,/g, ''); final = `${t ? t.name + ' at ' + money(t.price) : 'Our price'} vs ${money(other)}: the gap is ${money(Math.abs((t ? t.price : 0) - other))}.\nWhat to say: "At ${money(other)} it is usually 4 to 6 to a room, meals extra, transfers extra, no captain. Ours includes ${p.policies.included}. No hidden costs. Send me their inclusion list; if it matches ours line by line, I match the price."\nNever cut the price first: offer the inclusion comparison, then a 24-hour hold.`; }
    else if (/\b(refund|cancel)/.test(r) && /\b(\d{1,2})\s*days?\b/.test(r)) { const d = +r.match(/\b(\d{1,2})\s*days?\b/)[1]; const p = await use('policies', {}); final = `${d} days before departure: ${d >= 15 ? 'everything except the advance is refunded; the advance stays transferable to another batch within 6 months.' : 'no cash refund, because hotels and transport are already paid; the advance (and the balance if paid) can be transferred to another batch within 6 months or to another traveller.'}\nPolicy: ${p.policies.cancellation}`; }
    else if (policyKey) { const p = await use('policies', {}); final = `${policyKey.charAt(0).toUpperCase() + policyKey.slice(1)}: ${p.policies[policyKey] || 'not set yet (add it in Set up)'}`; }
    else if (/\b(season|in season|good time|best time|weather)\b/.test(r) && DEST.find(r)) { const d = await use('destination', { name: DEST.find(r).name }); const m = monthIdx || new Date().getMonth() + 1; const st = DEST.seasonStatus(d, m); final = `${d.name} in ${DEST.MONTHS[m - 1]}: ${st}. Best months: ${d.season.map(x => DEST.MONTHS[x - 1]).join(', ')}${d.shoulder.length ? '; shoulder: ' + d.shoulder.map(x => DEST.MONTHS[x - 1]).join(', ') : ''}. Risks: ${(d.risks || []).join(', ') || 'none noted'}.`; }
    else if (/\b(visa|document|documents|passport|permit|papers|id proof)\b/.test(r) && DEST.find(r)) { const d = await use('destination', { name: DEST.find(r).name }); const intl = d.country !== 'India'; final = `${d.name} (${d.country}): ${intl ? `passport valid 6 months beyond travel, ${(d.permits || []).join('; ') || 'check visa rules'}, return ticket and hotel confirmation; carry travel insurance.` : `government photo ID for every traveller (Aadhaar or passport; kids: school ID or birth certificate)${(d.permits || []).length ? '; permits: ' + d.permits.join('; ') : ''}.`}`; }
    else if (/\b(seats?|left|worth|how many)\b/.test(r) && (tripNamed() || /\btrip|batch\b/.test(r))) { const trips = await use('trips', {}); const list = tripNamed() ? trips.filter(t => t.name === tripNamed().name) : trips; final = list.length ? list.map(t => `${t.name} ${t.date || ''}: ${t.seatsLeft} seats left of ${t.seats} (${t.booked} booked, ${t.holds} on hold)${/worth|value|revenue/.test(r) ? `, worth ${money(t.seatsLeft * t.price)} if they all sell` : ''}, ${money(t.price)} per person.`).join('\n') : 'No trips set up yet. Add them in Set up.'; }
    else if (/\b(plan|itinerary|day ?wise)\b/.test(r) && DEST.find(r)) { const p = await use('plan_trip', { requirements: request }); final = `${p.season || ''} ~${money(p.perPerson)} per person\n${(p.itinerary || []).join('\n')}\n${(p.findings || []).join('\n')}\n${(p.fixes || []).join('\n')}`; }
    else if (/\b(leaving|departing|departures?|which trips|trips (in|this|next))\b/.test(r)) { const trips = await use('trips', {}); const list = monthIdx ? trips.filter(t => t.date && new Date(t.date).getMonth() + 1 === monthIdx) : trips; final = list.length ? list.map(t => `${t.name}: ${t.date}, ${t.days} days, ${money(t.price)} per person, ${t.seatsLeft} seats left`).join('\n') : (monthIdx ? `No batch in ${DEST.MONTHS[monthIdx - 1]} yet.` : 'No trips set up yet.'); }
    else if (/\b(today|follow[- ]?up|due|pipeline|which lead|who should i)\b/.test(r)) { const t = await use('today', {}); const leads = await use('leads', {}); const open = leads.filter(l => !['lost', 'reviewed', 'travelled'].includes(l.stage)); const order = ['hold', 'advance', 'quoted', 'objection', 'qualified', 'new', 'balance']; const hot = open.sort((a, b) => order.indexOf(a.stage) - order.indexOf(b.stage))[0]; final = t.due.length ? `${t.due.length} follow-up${t.due.length > 1 ? 's' : ''} due:\n` + t.due.map(d => `• ${d.lead} (${d.trip || 'no trip'}, ${d.stage}, ${d.step}): ${d.message}`).join('\n') : (hot ? `Nothing is due by schedule. Message ${hot.name || hot.id} first: stage "${hot.stage}"${hot.trip ? ' for ' + hot.trip : ''}, the closest to money. ${g.followUp(leads.find(l => l.id === hot.id) ? g.state.leads.find(l => l.id === hot.id) : hot)}` : 'No leads yet. Post today\'s reel and the trip cards; leads come from there.') + (t.alerts.length ? '\nAlerts: ' + t.alerts.join(' ') : ''); }
    else if (/\b(instagram|reel|post|caption|content|google)\b/.test(r)) { const c = await use('content', {}); final = `Bio:\n${c.bio}\n\nThis week:\n${c.week.join('\n')}\n\nCaptions:\n${c.captions.join('\n')}\n\nGoogle posts:\n${c.googlePosts.join('\n')}`; }
    else if (/\b(plan|itinerary|days?|good idea|ok for|suitable)\b/.test(r) && DEST.find(r)) { const p = await use('plan_trip', { requirements: request }); final = `${p.season || ''} ~${money(p.perPerson)} per person\n${(p.itinerary || []).join('\n')}\n${(p.findings || []).join('\n')}\n${(p.fixes || []).join('\n')}`; }
    else if (/\b(lead|customer|wrote|said|replied|whatsapp)\b/.test(r) && /\n|:|"|'/.test(request)) { const msg = (request.match(/["“'‘](.+?)["”'’]/) || [])[1] || request.split(/\n|:/).slice(1).join(' ').trim() || request; const w = await use('whatsapp_reply', { text: msg }); final = `Reply to send:\n${w.reply}\n\n(${w.intent}${w.handoff ? ', needs you' : ''})`; }
    else if (/\b(price|cost|how much|rate)\b/.test(r)) { const trips = await use('trips', {}); const t = tripNamed() || trips[0]; final = t ? `${t.name}: ${money(t.price)} per person${n ? `, ${money(t.price * n)} for ${n}` : ''}, all-inclusive. ${t.seatsLeft} seats left.` : 'No trips set up yet.'; }
    else { const x = await use('recall', { query: request }); final = x.answer; }
    return { final: final + '\n\n(rules; connect a model in Set up for deeper reasoning)', steps };
  }

  /** The chief corrects an answer: the correction becomes a lesson, and the pairing is remembered for next time. */
  correct(id, correction) {
    const e = this.log.find(x => x.id === id); if (!e) return null;
    e.correction = String(correction || '');
    this.brain.teach(`When asked "${e.request.slice(0, 120)}", the right answer is: ${e.correction.slice(0, 300)}.\n${e.correction}`, { source: 'chief-correction', importance: 1 });
    this.brain.feedback(false, 'agent correction');
    return e;
  }
  approve(id) { const e = this.log.find(x => x.id === id); if (!e) return null; e.approved = true; this.brain.feedback(true, 'agent approved'); if (e.final) this.brain.teach(`A good answer to "${e.request.slice(0, 120)}" was: ${e.final.slice(0, 300)}.`, { source: 'chief-approval', importance: 0.7 }); return e; }
}
module.exports = { Agent, tools, SYSTEM };
