'use strict';
/**
 * geo.js — place-aware planning the way a good operations head does it by hand, made repeatable.
 *
 * 1. A hexagonal grid in the style of Uber's H3 (axial hex cells on a local tangent plane, three resolutions:
 *    8 km, 3 km, 1 km edges; cell ids, centres, k-rings). Zero dependencies; swap in h3-js later if wanted.
 * 2. Attractions per destination with coordinates, visit hours, time window (sunrise, morning, day, sunset, evening,
 *    night, full day), weekday closures and season.
 * 3. hotelZone(): the cell (and named area) whose hotel minimises hours-weighted travel to every attraction, with
 *    a pull towards the common pickup point. 4. plan(): a day-by-day itinerary that respects the time budget,
 *    windows, closures and the driving rules, with feasibility warnings. 5. rankHotels(): candidates scored by a
 *    Bayesian review average weighted by source reliability, stars, and distance to the ideal zone.
 */
const RULES = { dayStart: 8.5, dayEnd: 19.5, eveningEnd: 22.5, arrivalStart: 13, departureEnd: 15, maxDriveMinPerDay: 210, cityKmh: 32, roadKmh: 50, roadFactor: 1.3, stopBufferMin: 8, splitKm: 45 };
const SIZES = [8, 3, 1]; // km, hex edge per resolution
const SQ3 = Math.sqrt(3);
const rad = (d) => d * Math.PI / 180;
function haversine(a, b) { const dLat = rad(b.lat - a.lat), dLng = rad(b.lng - a.lng); const h = Math.sin(dLat / 2) ** 2 + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLng / 2) ** 2; return 2 * 6371 * Math.asin(Math.sqrt(h)); }
function toXY(p, o) { return { x: (p.lng - o.lng) * Math.cos(rad(o.lat)) * 111.32, y: (p.lat - o.lat) * 110.57 }; }
function toLatLng(xy, o) { return { lat: o.lat + xy.y / 110.57, lng: o.lng + xy.x / (111.32 * Math.cos(rad(o.lat))) }; }
function cubeRound(q, r) { let x = q, z = r, y = -x - z; let rx = Math.round(x), ry = Math.round(y), rz = Math.round(z); const dx = Math.abs(rx - x), dy = Math.abs(ry - y), dz = Math.abs(rz - z); if (dx > dy && dx > dz) rx = -ry - rz; else if (dy > dz) ry = -rx - rz; else rz = -rx - ry; return { q: rx, r: rz }; }
/** Cell for a point: {res, q, r, id}. Origin is the destination centre so ids are comparable within one place. */
function cell(p, o, res = 1) { const s = SIZES[res]; const { x, y } = toXY(p, o); const q = (SQ3 / 3 * x - y / 3) / s, r = (2 / 3 * y) / s; const c = cubeRound(q, r); return { res, q: c.q, r: c.r, id: `${res}:${c.q}:${c.r}` }; }
function center(c, o) { const s = SIZES[c.res]; const x = s * (SQ3 * c.q + SQ3 / 2 * c.r), y = s * (3 / 2 * c.r); return toLatLng({ x, y }, o); }
const DIRS = [[1, 0], [1, -1], [0, -1], [-1, 0], [-1, 1], [0, 1]];
function kRing(c, k) { const out = []; for (let dq = -k; dq <= k; dq++) for (let dr = Math.max(-k, -dq - k); dr <= Math.min(k, -dq + k); dr++) out.push({ res: c.res, q: c.q + dq, r: c.r + dr, id: `${c.res}:${c.q + dq}:${c.r + dr}` }); return out; }
function hexDistance(a, b) { return (Math.abs(a.q - b.q) + Math.abs(a.q + a.r - b.q - b.r) + Math.abs(a.r - b.r)) / 2; }
function travelMin(a, b, city = true) { const km = haversine(a, b) * RULES.roadFactor; const kmh = km > 40 ? RULES.roadKmh : city ? RULES.cityKmh : RULES.roadKmh; return Math.round(km / kmh * 60 + (km > 0.3 ? RULES.stopBufferMin : 0)); }

// window: sunrise (start by 6:30), morning (before 12), day, afternoon, sunset (last daylight slot), evening (after 18), night (after 20), full (whole day).
const PLACES = {
  goa: { name: 'Goa', center: { lat: 15.49, lng: 73.82 }, pickups: [{ name: 'Madgaon station', lat: 15.272, lng: 73.957 }, { name: 'Dabolim airport', lat: 15.380, lng: 73.831 }, { name: 'Mopa airport', lat: 15.747, lng: 73.864 }], areas: [{ name: 'Calangute', lat: 15.544, lng: 73.755 }, { name: 'Baga', lat: 15.556, lng: 73.751 }, { name: 'Candolim', lat: 15.518, lng: 73.762 }, { name: 'Panjim', lat: 15.497, lng: 73.828 }, { name: 'Anjuna', lat: 15.573, lng: 73.740 }, { name: 'Colva', lat: 15.279, lng: 73.912 }, { name: 'Palolem', lat: 15.010, lng: 74.023 }],
    attractions: [{ name: 'Baga beach and water sports', lat: 15.556, lng: 73.751, hours: 3, window: 'day' }, { name: 'Calangute beach', lat: 15.544, lng: 73.755, hours: 1.5, window: 'day' }, { name: 'Anjuna flea market', lat: 15.573, lng: 73.740, hours: 2, window: 'afternoon', days: [3] }, { name: 'Chapora fort', lat: 15.604, lng: 73.737, hours: 1, window: 'sunset' }, { name: 'Aguada fort and lighthouse', lat: 15.492, lng: 73.773, hours: 1.5, window: 'morning' }, { name: 'Panjim Fontainhas walk', lat: 15.497, lng: 73.830, hours: 1.5, window: 'morning' }, { name: 'Old Goa churches', lat: 15.500, lng: 73.912, hours: 2, window: 'morning' }, { name: 'Dudhsagar falls jeep safari', lat: 15.314, lng: 74.314, hours: 7, window: 'full', season: [10, 11, 12, 1, 2, 3, 4, 5] }, { name: 'Palolem beach', lat: 15.010, lng: 74.023, hours: 3, window: 'day' }, { name: 'Dona Paula viewpoint', lat: 15.456, lng: 73.805, hours: 1, window: 'sunset' }, { name: 'Mandovi river cruise', lat: 15.500, lng: 73.830, hours: 1.5, window: 'evening' }, { name: 'Titos lane, Baga', lat: 15.558, lng: 73.752, hours: 2, window: 'night' }, { name: 'Vagator beach', lat: 15.597, lng: 73.744, hours: 1.5, window: 'afternoon' }] },
  manali: { name: 'Manali', center: { lat: 32.24, lng: 77.19 }, pickups: [{ name: 'Manali bus stand', lat: 32.243, lng: 77.189 }, { name: 'Bhuntar airport', lat: 31.877, lng: 77.154 }], areas: [{ name: 'Mall Road', lat: 32.243, lng: 77.189 }, { name: 'Old Manali', lat: 32.254, lng: 77.179 }, { name: 'Vashisht', lat: 32.263, lng: 77.196 }, { name: 'Aleo and Prini', lat: 32.215, lng: 77.195 }, { name: 'Naggar road', lat: 32.17, lng: 77.17 }],
    attractions: [{ name: 'Hadimba temple', lat: 32.248, lng: 77.179, hours: 1.5, window: 'morning' }, { name: 'Mall Road and Tibetan market', lat: 32.243, lng: 77.189, hours: 2, window: 'evening' }, { name: 'Old Manali cafes', lat: 32.254, lng: 77.179, hours: 2, window: 'evening' }, { name: 'Vashisht hot springs', lat: 32.263, lng: 77.196, hours: 1.5, window: 'morning' }, { name: 'Solang valley (paragliding, zorbing)', lat: 32.317, lng: 77.157, hours: 4, window: 'day' }, { name: 'Atal tunnel and Sissu', lat: 32.479, lng: 77.128, hours: 5, window: 'full' }, { name: 'Rohtang pass', lat: 32.372, lng: 77.247, hours: 6, window: 'full', days: [1, 3, 4, 5, 6, 0], season: [5, 6, 7, 8, 9, 10] }, { name: 'Naggar castle and Roerich gallery', lat: 32.117, lng: 77.165, hours: 2.5, window: 'day' }, { name: 'Jogini falls walk', lat: 32.268, lng: 77.198, hours: 2.5, window: 'morning' }, { name: 'Kullu river rafting', lat: 31.958, lng: 77.109, hours: 2.5, window: 'day', season: [3, 4, 5, 6, 9, 10, 11] }, { name: 'Manu temple', lat: 32.258, lng: 77.178, hours: 1, window: 'afternoon' }] },
  bangkok: { name: 'Bangkok', center: { lat: 13.75, lng: 100.52 }, pickups: [{ name: 'Suvarnabhumi airport', lat: 13.690, lng: 100.750 }, { name: 'Don Mueang airport', lat: 13.913, lng: 100.607 }], areas: [{ name: 'Sukhumvit', lat: 13.738, lng: 100.561 }, { name: 'Pratunam', lat: 13.753, lng: 100.540 }, { name: 'Silom', lat: 13.726, lng: 100.527 }, { name: 'Riverside', lat: 13.722, lng: 100.511 }, { name: 'Khao San', lat: 13.759, lng: 100.497 }],
    attractions: [{ name: 'Grand Palace and Emerald Buddha', lat: 13.750, lng: 100.491, hours: 2.5, window: 'morning' }, { name: 'Wat Pho reclining Buddha', lat: 13.746, lng: 100.493, hours: 1.5, window: 'morning' }, { name: 'Wat Arun', lat: 13.744, lng: 100.489, hours: 1, window: 'sunset' }, { name: 'Chatuchak weekend market', lat: 13.800, lng: 100.550, hours: 3, window: 'morning', days: [6, 0] }, { name: 'Safari World and Marine Park', lat: 13.869, lng: 100.700, hours: 6, window: 'full' }, { name: 'Chao Phraya dinner cruise', lat: 13.744, lng: 100.511, hours: 2, window: 'evening' }, { name: 'ICONSIAM and Mahanakhon skywalk', lat: 13.726, lng: 100.510, hours: 2.5, window: 'afternoon' }, { name: 'Asiatique riverfront', lat: 13.705, lng: 100.503, hours: 2, window: 'evening' }, { name: 'Khao San road', lat: 13.759, lng: 100.497, hours: 2, window: 'night' }, { name: 'Floating market (Damnoen Saduak)', lat: 13.520, lng: 99.959, hours: 5, window: 'morning' }] },
  phuket: { name: 'Phuket', center: { lat: 7.89, lng: 98.33 }, pickups: [{ name: 'Phuket airport', lat: 8.113, lng: 98.317 }], areas: [{ name: 'Patong', lat: 7.896, lng: 98.297 }, { name: 'Karon', lat: 7.843, lng: 98.294 }, { name: 'Kata', lat: 7.820, lng: 98.298 }, { name: 'Old Town', lat: 7.885, lng: 98.388 }],
    attractions: [{ name: 'Patong beach', lat: 7.896, lng: 98.297, hours: 2.5, window: 'day' }, { name: 'Big Buddha', lat: 7.828, lng: 98.312, hours: 1.5, window: 'morning' }, { name: 'Promthep cape', lat: 7.761, lng: 98.305, hours: 1, window: 'sunset' }, { name: 'Phuket old town', lat: 7.885, lng: 98.388, hours: 2, window: 'afternoon' }, { name: 'Phi Phi islands speedboat (from Rassada pier)', lat: 7.874, lng: 98.405, hours: 8, window: 'full' }, { name: 'James Bond island (from Ao Po)', lat: 8.056, lng: 98.436, hours: 8, window: 'full' }, { name: 'Bangla road', lat: 7.895, lng: 98.297, hours: 2, window: 'night' }, { name: 'Karon viewpoint', lat: 7.820, lng: 98.305, hours: 0.75, window: 'afternoon' }, { name: 'Simon cabaret or Fantasea show', lat: 7.883, lng: 98.299, hours: 2.5, window: 'evening' }] },
  dubai: { name: 'Dubai', center: { lat: 25.20, lng: 55.27 }, pickups: [{ name: 'Dubai airport DXB', lat: 25.253, lng: 55.365 }], areas: [{ name: 'Deira', lat: 25.27, lng: 55.31 }, { name: 'Bur Dubai', lat: 25.255, lng: 55.30 }, { name: 'Al Barsha', lat: 25.11, lng: 55.20 }, { name: 'Downtown', lat: 25.20, lng: 55.27 }, { name: 'Marina', lat: 25.08, lng: 55.14 }],
    attractions: [{ name: 'Burj Khalifa and Dubai Mall fountain', lat: 25.197, lng: 55.274, hours: 3, window: 'sunset' }, { name: 'Dubai Frame', lat: 25.235, lng: 55.300, hours: 1.5, window: 'morning' }, { name: 'Gold and spice souk, abra ride', lat: 25.284, lng: 55.299, hours: 2, window: 'morning' }, { name: 'Dubai Marina walk and yacht cruise', lat: 25.080, lng: 55.140, hours: 2.5, window: 'evening' }, { name: 'Palm Jumeirah and Atlantis', lat: 25.130, lng: 55.117, hours: 2, window: 'afternoon' }, { name: 'Desert safari (pickup 3 pm)', lat: 25.100, lng: 55.400, hours: 6, window: 'afternoon' }, { name: 'Miracle Garden', lat: 25.061, lng: 55.244, hours: 2, window: 'morning', season: [11, 12, 1, 2, 3, 4] }, { name: 'Global Village', lat: 25.069, lng: 55.307, hours: 3, window: 'evening', season: [10, 11, 12, 1, 2, 3, 4] }, { name: 'Abu Dhabi: Grand Mosque and Ferrari World', lat: 24.412, lng: 54.475, hours: 9, window: 'full' }, { name: 'Jumeirah beach and Burj Al Arab view', lat: 25.141, lng: 55.185, hours: 1.5, window: 'afternoon' }, { name: 'Museum of the Future', lat: 25.219, lng: 55.282, hours: 2, window: 'morning' }] },
  kerala: { name: 'Kerala', center: { lat: 9.97, lng: 76.28 }, pickups: [{ name: 'Kochi airport', lat: 10.152, lng: 76.401 }], areas: [{ name: 'Fort Kochi', lat: 9.965, lng: 76.242 }, { name: 'Ernakulam', lat: 9.977, lng: 76.276 }, { name: 'Munnar town', lat: 10.089, lng: 77.060 }, { name: 'Thekkady', lat: 9.600, lng: 77.165 }, { name: 'Alleppey', lat: 9.498, lng: 76.338 }],
    attractions: [{ name: 'Fort Kochi, Chinese nets, Jew Town', lat: 9.965, lng: 76.242, hours: 3, window: 'afternoon' }, { name: 'Kathakali show', lat: 9.964, lng: 76.244, hours: 1.5, window: 'evening' }, { name: 'Munnar tea gardens and tea museum', lat: 10.089, lng: 77.060, hours: 3, window: 'day' }, { name: 'Eravikulam park (Nilgiri tahr)', lat: 10.148, lng: 77.062, hours: 2.5, window: 'morning', season: [4, 5, 6, 7, 8, 9, 10, 11, 12, 1] }, { name: 'Mattupetty dam and Echo point', lat: 10.106, lng: 77.125, hours: 2, window: 'afternoon' }, { name: 'Top station sunrise', lat: 10.126, lng: 77.248, hours: 2, window: 'sunrise' }, { name: 'Periyar lake boat and spice garden', lat: 9.590, lng: 77.160, hours: 3.5, window: 'morning' }, { name: 'Alleppey houseboat (check-in noon)', lat: 9.498, lng: 76.338, hours: 6, window: 'full' }, { name: 'Marine Drive walk', lat: 9.977, lng: 76.276, hours: 1, window: 'evening' }] },
};
const ALIASES = { calangute: 'goa', panjim: 'goa', 'north goa': 'goa', 'south goa': 'goa', solang: 'manali', kullu: 'manali', thailand: 'bangkok', pattaya: 'bangkok', krabi: 'phuket', uae: 'dubai', 'abu dhabi': 'dubai', kochi: 'kerala', munnar: 'kerala', alleppey: 'kerala', cochin: 'kerala' };
function place(name) { const q = String(name || '').toLowerCase(); if (PLACES[q]) return { key: q, ...PLACES[q] }; for (const [a, k] of Object.entries(ALIASES)) if (q.includes(a)) return { key: k, ...PLACES[k] }; for (const k of Object.keys(PLACES)) if (q.includes(k)) return { key: k, ...PLACES[k] }; return null; }

/** Where the hotel should be: rank candidate cells (and named areas) by hours-weighted travel to every attraction plus a pull to the pickup point. */
function hotelZone(name, { pickup, res = 1, pickupWeight = 0.25 } = {}) {
  const P = place(name); if (!P) return null; const o = P.center; const pk = pickup ? (P.pickups.find(x => new RegExp(pickup, 'i').test(x.name)) || P.pickups[0]) : P.pickups[0];
  const main = P.attractions.filter(a => a.window !== 'full' || haversine(a, o) < RULES.splitKm); // full-day excursions pull the hotel too far
  const cells = new Map(); for (const a of P.attractions) for (const c of kRing(cell(a, o, res), 2)) cells.set(c.id, c); for (const ar of P.areas) cells.set(cell(ar, o, res).id, cell(ar, o, res));
  const scored = [...cells.values()].map(c => { const ctr = center(c, o); const w = main.reduce((n, a) => n + a.hours * travelMin(ctr, a), 0) / main.reduce((n, a) => n + a.hours, 0); const pm = travelMin(ctr, pk, false); return { cell: c, center: ctr, avgMinToAttractions: Math.round(w), minToPickup: pm, score: Math.round(w + pickupWeight * pm) }; }).sort((a, b) => a.score - b.score);
  const areas = P.areas.map(ar => { const w = main.reduce((n, a) => n + a.hours * travelMin(ar, a), 0) / main.reduce((n, a) => n + a.hours, 0); const pm = travelMin(ar, pk, false); return { area: ar.name, avgMinToAttractions: Math.round(w), minToPickup: pm, score: Math.round(w + pickupWeight * pm) }; }).sort((a, b) => a.score - b.score);
  return { place: P.name, pickup: pk.name, bestCell: scored[0], areas, note: 'Lower is better: average minutes to attractions weighted by time spent there, plus a quarter of the minutes to the pickup point.' };
}

/** Day-by-day plan with feasibility. days = number of full days; date (optional) fixes weekdays and season. */
function plan(name, days = 3, { date, pickup, base } = {}) {
  const P = place(name); if (!P) return null; const o = P.center; const start = date ? new Date(date) : null; const month = start ? start.getMonth() + 1 : null;
  const zone = hotelZone(name, { pickup }); const baseArea = base ? P.areas.find(a => new RegExp(base, 'i').test(a.name)) || P.areas[0] : P.areas.find(a => a.name === zone.areas[0].area);
  const warnings = []; let pool = P.attractions.filter(a => !(a.season && month && !a.season.includes(month)) || (warnings.push(`${a.name}: out of season in month ${month}, left out.`), false));
  // Group far-away attractions (over splitKm from the base) into excursion days from the base, or a second base when there are many.
  const far = pool.filter(a => haversine(a, baseArea) > RULES.splitKm && a.window !== 'full'); const secondBase = far.length >= 3 ? (P.areas.filter(ar => ar !== baseArea).map(ar => ({ ar, d: far.reduce((n, a) => n + haversine(a, ar), 0) })).sort((x, y) => x.d - y.d)[0] || {}).ar : null;
  const dayPlans = []; const used = new Set(); const dow = (i) => start ? (start.getDay() + i) % 7 : null;
  const order = ['sunrise', 'morning', 'day', 'afternoon', 'sunset', 'evening', 'night']; const rank = (w) => order.indexOf(w);
  for (let d = 0; d < days; d++) {
    const dayBase = secondBase && d >= Math.ceil(days / 2) ? secondBase : baseArea; const dd = dow(d); const arrival = d === 0 && days >= 2, departure = d === days - 1 && days >= 3;
    let cands = pool.filter(a => !used.has(a.name) && !(a.days && dd != null && !a.days.includes(dd)));
    if (secondBase) cands = cands.filter(a => (dayBase === secondBase) === (haversine(a, secondBase) < haversine(a, baseArea)));
    const full = !arrival && !departure ? cands.find(a => a.window === 'full') : null; const items = []; let t = arrival ? RULES.arrivalStart : RULES.dayStart, drive = 0, at = dayBase; const dayEnd = departure ? RULES.departureEnd : RULES.dayEnd, eveEnd = departure ? RULES.departureEnd : RULES.eveningEnd;
    if (full) { const tm = travelMin(dayBase, full, false); items.push({ time: t, name: full.name, hours: full.hours, driveMin: tm }); used.add(full.name); drive += 2 * tm; t += full.hours + (2 * tm) / 60; dayPlans.push({ day: d + 1, base: dayBase.name, items, driveMin: drive, ends: t, full: true, weekday: dd }); continue; }
    cands = cands.filter(a => a.window !== 'full').sort((a, b) => rank(a.window) - rank(b.window) || travelMin(dayBase, a) - travelMin(dayBase, b));
    for (const w of order) { for (const a of cands.filter(x => x.window === w).sort((x, y) => travelMin(at, x) - travelMin(at, y))) { const tm = travelMin(at, a); const startAt = Math.max(t + tm / 60, w === 'evening' ? 18 : w === 'night' ? 20 : w === 'sunset' ? 16.5 : w === 'afternoon' ? 13 : 0); const limit = ['evening', 'night'].includes(w) ? eveEnd : dayEnd; if (startAt + a.hours > limit || drive + tm > RULES.maxDriveMinPerDay + 60) continue; if (w === 'morning' && startAt >= 12) continue; items.push({ time: startAt, name: a.name, hours: a.hours, driveMin: tm }); used.add(a.name); t = startAt + a.hours; drive += tm; at = a; if (items.length >= 6) break; } if (items.length >= 6) break; }
    drive += travelMin(at, dayBase); dayPlans.push({ day: d + 1, base: dayBase.name, items, driveMin: drive, ends: t, weekday: dd, note: arrival ? 'arrival day: pickup, check-in, light afternoon' : departure ? 'departure day: checkout, one stop, drop' : '' });
  }
  const left = pool.filter(a => !used.has(a.name)); for (const a of left) warnings.push(`${a.name} did not fit in ${days} days${a.days ? ' (only on ' + a.days.map(x => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][x]).join(', ') + ')' : ''}; add a day or drop it.`);
  for (const dp of dayPlans) { if (dp.driveMin > RULES.maxDriveMinPerDay && !dp.full) warnings.push(`Day ${dp.day}: ${dp.driveMin} minutes in the vehicle, over the ${RULES.maxDriveMinPerDay} minute city limit; regroup by area.`); if (!dp.items.length) warnings.push(`Day ${dp.day}: empty; shorten the trip or add attractions.`); }
  const score = Math.round(100 * (1 - Math.min(1, (left.length * 0.08 + dayPlans.filter(x => x.driveMin > RULES.maxDriveMinPerDay && !x.full).length * 0.15 + dayPlans.filter(x => !x.items.length).length * 0.3))));
  return { place: P.name, days, base: baseArea.name, secondBase: secondBase ? secondBase.name : null, pickup: zone.pickup, hotelZone: zone.areas.slice(0, 3), plan: dayPlans, warnings, feasibility: score };
}
const hhmm = (h) => `${String(Math.floor(h)).padStart(2, '0')}:${String(Math.round((h % 1) * 60)).padStart(2, '0')}`;
function planText(p) { if (!p) return 'No map data for that place yet (have: ' + Object.keys(PLACES).join(', ') + ').'; const L = [`${p.place}, ${p.days} days · hotel zone: ${p.hotelZone.map(a => `${a.area} (${a.avgMinToAttractions} min avg to sights, ${a.minToPickup} min to ${p.pickup})`).join('; ')}${p.secondBase ? ' · second base ' + p.secondBase : ''} · feasibility ${p.feasibility}%`]; for (const d of p.plan) L.push(`Day ${d.day} (${d.base})${d.weekday != null ? ' ' + ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][d.weekday] : ''}${d.note ? ' · ' + d.note : ''}: ${d.items.map(i => `${hhmm(i.time)} ${i.name} (${i.hours} h${i.driveMin ? ', ' + i.driveMin + ' min drive' : ''})`).join(' → ') || 'free'} · in the vehicle ${d.driveMin} min`); if (p.warnings.length) L.push('Checks: ' + p.warnings.join(' ')); return L.join('\n'); }

/** Hotel candidates: {name, area|lat,lng, stars, rating (0-5), reviews, source, price}. Bayesian average towards a 4.1 prior with 100 pseudo-reviews, source reliability, stars, distance to the ideal zone. */
const SOURCE = { google: 1, booking: 1, 'booking.com': 1, tripadvisor: 0.9, makemytrip: 0.85, mmt: 0.85, agoda: 0.85, goibibo: 0.8, expedia: 0.85, own: 0.4, website: 0.4, unknown: 0.6 };
function rankHotels(cands, { place: name, pickup } = {}) {
  const P = name ? place(name) : null; const zone = P ? hotelZone(P.key, { pickup }) : null; const ideal = zone ? zone.bestCell.center : null;
  const rows = (cands || []).map(h => { const rating = +h.rating || 0, n = +h.reviews || 0; const src = SOURCE[String(h.source || 'unknown').toLowerCase()] ?? 0.6; const bayes = (rating * n + 4.1 * 100) / (n + 100); const review = Math.max(0, Math.min(1, (bayes - 3.5) / 1.5)) * (0.7 + 0.3 * src) * (n >= 50 ? 1 : 0.8); const stars = Math.min(1, (+h.stars || 3) / 5); let loc = 0.5, km = null, areaName = h.area || ''; if (P) { let pt = h.lat && h.lng ? { lat: +h.lat, lng: +h.lng } : (P.areas.find(a => h.area && new RegExp(h.area, 'i').test(a.name)) || null); if (pt) { km = haversine(pt, ideal); loc = Math.max(0, 1 - km / 15); areaName = areaName || pt.name || ''; } } const score = Math.round(100 * (0.5 * review + 0.2 * stars + 0.3 * loc)); const why = [`reviews ${rating}/5 from ${n} on ${h.source || 'unknown'} → ${bayes.toFixed(2)} adjusted${n < 50 ? ' (under 50 reviews, trusted less)' : ''}`, `${h.stars || '?'} star`, km != null ? `${km.toFixed(1)} km from the ideal zone` : 'no location given']; return { name: h.name, area: areaName, score, price: h.price || null, why }; }).sort((a, b) => b.score - a.score);
  return { ideal: zone ? zone.areas[0].area : null, ranked: rows, rule: 'Pick the top one unless its price breaks the margin; never a hotel under 50 reviews on a reliable source without a site visit.' };
}
function parseHotels(text) { return String(text || '').split(/\n|;/).map(l => l.trim()).filter(Boolean).map(l => { const p = l.split(/\s*[,|]\s*/); if (p.length < 4) return null; const num = (x) => +String(x || '').replace(/[^\d.]/g, ''); return { name: p[0], area: p[1], stars: num(p[2]), rating: num(p[3]), reviews: num(p[4]), source: (p[5] || 'unknown').toLowerCase(), price: p[6] ? num(p[6]) : null }; }).filter(Boolean); }
module.exports = { RULES, SIZES, PLACES, haversine, cell, center, kRing, hexDistance, travelMin, place, hotelZone, plan, planText, rankHotels, parseHotels };
