'use strict';
/**
 * routing.js — how the clan actually gets people there: road legs with km and hours, halts, hazards by season,
 * train and flight options, and the driving rules a batch must obey. Keyed by destination; routes start from the
 * company city (Ahmedabad by default) or from the gateway (airport or railhead) the plan flies into.
 *
 * journey() writes the one-line "how we travel" for quotes and the pre-departure brief; check() audits a plan
 * (too many km in the hills, night driving, altitude gained too fast, monsoon ghats); nearest() finds the gateway.
 */
const RULES = { plainsKmPerDay: 600, hillsKmPerDay: 300, driverRestHours: 4, noNightDrivingHills: true, sleepGainAbove2500m: 500, bufferPerLegPct: 15 };
// Each leg: [from, to, km, hours, note]. hills: true applies the hill limits. gateway: where flyers or train travellers join.
const ROUTES = {
  goa: { from: 'Ahmedabad', km: 1000, bus: 18, train: 14, flight: 1.4, gateway: 'Goa airport (Dabolim or Mopa)', legs: [['Ahmedabad', 'Vadodara', 110, 2, 'expressway'], ['Vadodara', 'Surat', 150, 2.5, ''], ['Surat', 'Mumbai outskirts', 280, 5, 'traffic after 4 pm'], ['Mumbai', 'Pune', 150, 3, 'expressway'], ['Pune', 'Kolhapur', 230, 4, 'dinner halt'], ['Kolhapur', 'Panjim', 230, 5, 'Amboli ghat, slow in monsoon']], plan: 'Overnight AC sleeper bus or the Okha–Ernakulam train to Madgaon; flyers meet the group at the hotel by 2 pm', hazards: ['Amboli and Chorla ghats in July to September', 'Mumbai stretch 4 to 8 pm'], season: 'November to February best; monsoon beaches closed for swimming' },
  manali: { from: 'Ahmedabad', km: 1550, bus: 32, train: 14, flight: 1.5, gateway: 'Delhi (then Volvo 12 to 14 h) or Bhuntar airport 50 km', legs: [['Ahmedabad', 'Udaipur', 260, 5, ''], ['Udaipur', 'Jaipur', 400, 7, 'night halt Jaipur'], ['Jaipur', 'Delhi', 280, 5, ''], ['Delhi', 'Chandigarh', 250, 5, ''], ['Chandigarh', 'Mandi', 200, 5, 'hills begin'], ['Mandi', 'Manali', 110, 3.5, 'Kullu valley, Pandoh dam slow']], hills: true, plan: 'Train to Delhi (Ashram Express or Rajdhani), then a Volvo from Delhi at 6 pm reaching Manali by 8 am; the bus stops at Mandi for breakfast', hazards: ['Pandoh to Mandi landslides in July to September', 'Snow on Atal tunnel approach in January to February'], season: 'October to June; snow December to February' },
  ladakh: { from: 'Delhi', km: 1010, bus: 0, train: 0, flight: 1.3, gateway: 'Leh airport (fly from Delhi); road only via Manali or Srinagar', legs: [['Manali', 'Jispa', 100, 4, 'Atal tunnel, sleep at 3,200 m'], ['Jispa', 'Sarchu', 90, 4, 'Baralacha La 4,890 m'], ['Sarchu', 'Leh', 255, 8, 'Nakee La, Lachulung La, Tanglang La 5,328 m'], ['Leh', 'Nubra (Hunder)', 125, 5, 'Khardung La 5,359 m'], ['Nubra', 'Pangong', 160, 6, 'Shyok road, river crossings before noon'], ['Pangong', 'Leh', 225, 6, 'Chang La 5,360 m']], hills: true, plan: 'Fly Delhi to Leh, two rest days at 3,500 m before Khardung La; Nubra, then Pangong by the Shyok road, back via Chang La; road entry from Manali only with a night at Jispa', hazards: ['Altitude: 2 acclimatisation days are non-negotiable', 'Shyok road river crossings after 1 pm', 'Khardung La and Chang La close in snow'], season: 'June to September; Manali road open roughly June to October' },
  spiti: { from: 'Shimla', km: 420, bus: 0, train: 0, flight: 1.2, gateway: 'Chandigarh airport, then Shimla; return via Manali (Kunzum, June to October)', legs: [['Shimla', 'Sarahan', 170, 6, 'Kinnaur road, one-lane cuttings'], ['Sarahan', 'Kalpa', 100, 4, ''], ['Kalpa', 'Tabo', 160, 7, 'Nako at 3,600 m, Malling slide zone'], ['Tabo', 'Kaza', 50, 1.5, 'Dhankar on the way'], ['Kaza', 'Chandratal', 100, 5, 'Kunzum La 4,590 m'], ['Chandratal', 'Manali', 125, 7, 'Rohtang or Atal tunnel']], hills: true, plan: 'Shimla side up (gradual altitude), Manali side down; the only right order from June to October', hazards: ['Malling nallah and Pooh slides in monsoon', 'Chandratal camps close with the first snow'], season: 'June to October; winter Spiti is a different expedition' },
  kutch: { from: 'Ahmedabad', km: 330, bus: 6, train: 7, flight: 1, gateway: 'Bhuj airport or Bhuj railway station', legs: [['Ahmedabad', 'Bhuj', 330, 6, 'Surajbari bridge'], ['Bhuj', 'Dhordo (Rann)', 85, 2, 'Bhirandiyara dabeli halt'], ['Bhuj', 'Mandvi', 60, 1.5, 'beach']], plan: 'Day drive to Bhuj, Rann Utsav tents or Hodka village stay, Mandvi beach on the way back', hazards: ['Full-moon weekends sold out; book the tents 60 days out'], season: 'November to February (Rann Utsav)' },
  udaipur: { from: 'Ahmedabad', km: 260, bus: 5, train: 5, flight: 0, gateway: 'Udaipur airport or Udaipur City station', legs: [['Ahmedabad', 'Himmatnagar', 80, 1.5, ''], ['Himmatnagar', 'Udaipur', 180, 3.5, 'Shamlaji border, Aravalli ghat']], plan: 'Morning drive, lunch in Udaipur; Kumbhalgarh and Ranakpur as a day loop (160 km)', hazards: [], season: 'October to March' },
  jaisalmer: { from: 'Ahmedabad', km: 730, bus: 13, train: 12, flight: 0, gateway: 'Jodhpur airport (280 km) or Jaisalmer station', legs: [['Ahmedabad', 'Jodhpur', 450, 8, 'night halt Jodhpur'], ['Jodhpur', 'Jaisalmer', 280, 5, 'Pokaran'], ['Jaisalmer', 'Sam dunes', 45, 1, 'camp']], plan: 'Jodhpur night, Jaisalmer fort day, Sam dunes camp night, back via Jodhpur or the Jaisalmer–Ahmedabad train', hazards: ['Sandstorms in April to June', 'Fog on the Jodhpur road in January mornings'], season: 'October to March; desert festival in February' },
  mountabu: { from: 'Ahmedabad', km: 220, bus: 4.5, train: 4, flight: 0, gateway: 'Abu Road station (27 km)', legs: [['Ahmedabad', 'Palanpur', 150, 2.5, ''], ['Palanpur', 'Mount Abu', 70, 2, 'hill ghat, 20 hairpins']], hills: true, plan: 'Weekend drive, Nakki lake evening, Guru Shikhar sunrise', hazards: ['Ghat fog in winter mornings'], season: 'All year; peak December' },
  diu: { from: 'Ahmedabad', km: 360, bus: 7, train: 8, flight: 1, gateway: 'Diu airport or Veraval station', legs: [['Ahmedabad', 'Bhavnagar', 170, 3, ''], ['Bhavnagar', 'Diu', 190, 4, 'coastal road, slow villages']], plan: 'Long weekend drive, Nagoa beach, Somnath on the way back', hazards: [], season: 'October to March' },
  dwarka: { from: 'Ahmedabad', km: 440, bus: 8, train: 8, flight: 0, gateway: 'Jamnagar airport (130 km) or Dwarka station', legs: [['Ahmedabad', 'Rajkot', 215, 3.5, 'expressway'], ['Rajkot', 'Jamnagar', 90, 1.5, ''], ['Jamnagar', 'Dwarka', 135, 3, ''], ['Dwarka', 'Somnath', 230, 5, 'Porbandar coast']], plan: 'Dwarka darshan early morning, Bet Dwarka boat, Somnath aarti the next evening', hazards: ['Ferry to Bet Dwarka stops in rough sea'], season: 'October to March; Janmashtami crowds' },
  saputara: { from: 'Ahmedabad', km: 250, bus: 5, train: 0, flight: 0, gateway: 'Surat (160 km)', legs: [['Ahmedabad', 'Surat', 260, 4.5, 'expressway'], ['Surat', 'Saputara', 160, 3.5, 'Dang forest ghat']], hills: true, plan: 'Monsoon weekend, Gira falls, sunset point', hazards: ['Ghat waterfalls flood the road in heavy rain'], season: 'July to September for monsoon, October to February for weather' },
  kerala: { from: 'Kochi', km: 520, bus: 0, train: 0, flight: 2.5, gateway: 'Kochi airport (fly Ahmedabad via Mumbai or direct)', legs: [['Kochi', 'Munnar', 130, 4, 'tea-estate ghat'], ['Munnar', 'Thekkady', 90, 3, 'spice road'], ['Thekkady', 'Alleppey', 140, 4, 'houseboat check-in 12 noon'], ['Alleppey', 'Varkala', 120, 3, ''], ['Varkala', 'Trivandrum airport', 50, 1.5, '']], hills: true, plan: 'Fly in to Kochi, loop clockwise, fly out of Trivandrum', hazards: ['Munnar ghat fog at dawn', 'Houseboats need noon check-in'], season: 'October to March; monsoon for Ayurveda' },
  meghalaya: { from: 'Guwahati', km: 330, bus: 0, train: 0, flight: 3.5, gateway: 'Guwahati airport (via Delhi or Kolkata)', legs: [['Guwahati', 'Shillong', 100, 3, 'Umiam lake'], ['Shillong', 'Cherrapunji', 55, 2, ''], ['Cherrapunji', 'Dawki', 80, 3, 'Mawlynnong on the way'], ['Dawki', 'Shillong', 85, 3, '']], hills: true, plan: 'Shillong base, Cherrapunji root bridge day (3,500 steps), Dawki river, back to Guwahati', hazards: ['Root-bridge trek is 3 to 4 hours of steps; not for knees', 'Rain any month'], season: 'October to May; rain June to September' },
  sikkim: { from: 'Bagdogra', km: 500, bus: 0, train: 0, flight: 3, gateway: 'Bagdogra airport (via Delhi or Kolkata) or NJP station', legs: [['Bagdogra', 'Gangtok', 125, 4.5, 'Teesta road'], ['Gangtok', 'Lachung', 115, 6, 'North Sikkim permit'], ['Lachung', 'Yumthang', 25, 1.5, ''], ['Lachung', 'Gangtok', 115, 6, ''], ['Gangtok', 'Nathula', 55, 2.5, 'permit, closed Mon and Tue'], ['Gangtok', 'Bagdogra', 125, 4.5, '']], hills: true, plan: 'Gangtok two nights, Lachung two nights, Nathula day with Tsomgo lake', hazards: ['North Sikkim road closures after rain', 'Altitude at Gurudongmar 5,180 m'], season: 'March to May and October to December' },
  andaman: { from: 'Port Blair', km: 0, bus: 0, train: 0, flight: 4, gateway: 'Port Blair airport (via Chennai, Kolkata or Delhi)', legs: [['Port Blair', 'Havelock (Swaraj Dweep)', 60, 2, 'ferry, book 30 days out'], ['Havelock', 'Neil (Shaheed Dweep)', 25, 1, 'ferry'], ['Neil', 'Port Blair', 40, 1.5, 'ferry']], plan: 'Port Blair cellular jail evening, Havelock three nights, Neil one, ferries pre-booked', hazards: ['Ferries cancel in rough sea; keep a buffer day before the flight'], season: 'October to May' },
  rishikesh: { from: 'Delhi', km: 240, bus: 6, train: 5, flight: 0, gateway: 'Delhi, then road; Dehradun airport 35 km', legs: [['Delhi', 'Haridwar', 220, 5, ''], ['Haridwar', 'Rishikesh', 25, 1, '']], plan: 'Overnight train or bus from Delhi, camps on the Ganga, rafting 16 km stretch', hazards: ['Rafting closed July to mid-September'], season: 'September to June' },
  kashmir: { from: 'Srinagar', km: 400, bus: 0, train: 0, flight: 2.5, gateway: 'Srinagar airport (via Delhi)', legs: [['Srinagar', 'Gulmarg', 50, 2, ''], ['Gulmarg', 'Srinagar', 50, 2, ''], ['Srinagar', 'Pahalgam', 95, 3, ''], ['Pahalgam', 'Srinagar', 95, 3, ''], ['Srinagar', 'Sonamarg', 80, 2.5, '']], hills: true, plan: 'Houseboat night, Gulmarg gondola day, Pahalgam two nights, Sonamarg day', hazards: ['Check the news desk before every batch', 'Gondola closes in high wind'], season: 'April to October; snow December to February' },
  varanasi: { from: 'Varanasi', km: 0, bus: 0, train: 0, flight: 2, gateway: 'Varanasi airport (direct from Ahmedabad)', legs: [['Varanasi', 'Sarnath', 12, 0.5, ''], ['Varanasi', 'Ayodhya', 220, 5, 'optional']], plan: 'Ganga aarti evening, sunrise boat, Sarnath afternoon', hazards: ['Ghats slippery in monsoon flood'], season: 'October to March; Dev Deepawali in November' },
  hampi: { from: 'Hubli', km: 165, bus: 0, train: 0, flight: 2, gateway: 'Hubli airport or Hospet station', legs: [['Hubli', 'Hampi', 165, 3.5, '']], plan: 'Two full days by cycle and tuk-tuk, Hippie island sunset', hazards: ['Heat after 11 am in March to May'], season: 'October to February' },
  coorg: { from: 'Bangalore', km: 250, bus: 6, train: 0, flight: 2.5, gateway: 'Bangalore or Mangalore airport', legs: [['Bangalore', 'Mysore', 145, 3, ''], ['Mysore', 'Coorg (Madikeri)', 120, 3, 'ghat']], hills: true, plan: 'Mysore palace stop, coffee estate stay, Abbey falls and Dubare elephants', hazards: ['Landslides in August'], season: 'October to March' },
  ooty: { from: 'Coimbatore', km: 85, bus: 3, train: 5, flight: 2.5, gateway: 'Coimbatore airport', legs: [['Coimbatore', 'Mettupalayam', 40, 1, ''], ['Mettupalayam', 'Ooty', 45, 2, 'toy train 5 h or road 2 h']], hills: true, plan: 'Toy train up, road down, Coonoor tea day', hazards: ['Toy train sells out; book 60 days out'], season: 'All year; peak April to June' },
  thailand: { from: 'Bangkok', km: 0, bus: 0, train: 0, flight: 4.5, gateway: 'Bangkok (direct from Ahmedabad, 4.5 h)', legs: [['Bangkok', 'Pattaya', 150, 2.5, 'van'], ['Pattaya', 'Bangkok', 150, 2.5, ''], ['Bangkok', 'Phuket', 0, 1.4, 'flight'], ['Phuket', 'Krabi', 165, 3, 'van or ferry']], plan: 'Bangkok two nights, Pattaya two, fly to Phuket for three; Phi Phi by speedboat', hazards: ['Phi Phi boats cancel in rough sea May to October', 'Pattaya road traffic on Friday evening'], season: 'November to March; monsoon May to October on the west coast' },
  dubai: { from: 'Dubai', km: 0, bus: 0, train: 0, flight: 3, gateway: 'Dubai (direct from Ahmedabad, 3 h)', legs: [['Dubai', 'Abu Dhabi', 140, 1.5, 'Sheikh Zayed road'], ['Dubai', 'Desert camp', 50, 1, '4x4 pickup']], plan: 'Metro for the city, van for Abu Dhabi day, desert safari pickup from the hotel', hazards: ['Heat June to September; outdoor only after 5 pm'], season: 'November to March' },
  bali: { from: 'Denpasar', km: 0, bus: 0, train: 0, flight: 9, gateway: 'Denpasar via Singapore or Kuala Lumpur (9 to 11 h with the stop)', legs: [['Kuta', 'Ubud', 35, 1.5, 'traffic'], ['Ubud', 'Kintamani', 40, 1.5, ''], ['Ubud', 'Uluwatu', 50, 2, ''], ['Kuta', 'Nusa Penida', 0, 0.75, 'fast boat from Sanur']], plan: 'Kuta or Seminyak three nights, Ubud three, Nusa Penida day trip', hazards: ['Nusa Penida boats and roads are rough', 'Kuta traffic after 4 pm'], season: 'April to October dry; rain December to February' },
  vietnam: { from: 'Hanoi', km: 0, bus: 0, train: 0, flight: 7, gateway: 'Hanoi or Ho Chi Minh via Delhi or Bangkok', legs: [['Hanoi', 'Halong Bay', 170, 3, 'cruise embarks 12 noon'], ['Hanoi', 'Da Nang', 0, 1.3, 'flight'], ['Da Nang', 'Hoi An', 30, 1, ''], ['Da Nang', 'Ba Na Hills', 40, 1.5, '']], plan: 'Hanoi two nights, Halong cruise one night, fly to Da Nang for Hoi An and Ba Na', hazards: ['Halong cruises cancel in typhoon warnings August to October'], season: 'October to April' },
  srilanka: { from: 'Colombo', km: 0, bus: 0, train: 0, flight: 4, gateway: 'Colombo via Mumbai or Chennai', legs: [['Colombo', 'Kandy', 115, 3.5, ''], ['Kandy', 'Ella', 0, 6.5, 'scenic train, book a reserved car'], ['Ella', 'Galle', 200, 5, ''], ['Galle', 'Colombo', 130, 2.5, 'expressway']], plan: 'Kandy, the Ella train, south coast beaches, back by expressway', hazards: ['Train reserved seats sell out 30 days ahead'], season: 'December to April for the south and west' },
  singapore: { from: 'Singapore', km: 0, bus: 0, train: 0, flight: 5.5, gateway: 'Singapore (direct from Ahmedabad, 5.5 h)', legs: [['Singapore', 'Kuala Lumpur', 350, 5, 'coach, border stop'], ['Kuala Lumpur', 'Genting', 50, 1.5, '']], plan: 'Singapore three nights on the MRT, coach to KL, Genting day', hazards: ['Causeway queues on Friday and Sunday'], season: 'All year; rain November to January' },
  nepal: { from: 'Kathmandu', km: 0, bus: 0, train: 0, flight: 1.7, gateway: 'Kathmandu via Delhi (1 h 40)', legs: [['Kathmandu', 'Pokhara', 200, 7, 'Prithvi highway, slow'], ['Pokhara', 'Kathmandu', 0, 0.5, 'flight option'], ['Kathmandu', 'Nagarkot', 30, 1.5, '']], hills: true, plan: 'Kathmandu two nights, drive to Pokhara (or fly back), Nagarkot sunrise', hazards: ['Highway landslides in monsoon', 'Domestic flights delay in fog December to January'], season: 'October to November and March to April' },
  bhutan: { from: 'Bagdogra', km: 380, bus: 0, train: 0, flight: 3, gateway: 'Bagdogra airport, road entry at Phuentsholing (Paro flights are costly)', legs: [['Bagdogra', 'Phuentsholing', 160, 4, 'permit at the gate'], ['Phuentsholing', 'Thimphu', 165, 5, 'hill road'], ['Thimphu', 'Punakha', 75, 3, 'Dochula pass'], ['Punakha', 'Paro', 125, 4, ''], ['Paro', 'Phuentsholing', 175, 5, '']], hills: true, plan: 'Road entry via Phuentsholing, Thimphu two nights, Punakha, Paro with the Tiger Nest hike (4 to 5 h)', hazards: ['Tiger Nest hike needs fitness; horses available half way'], season: 'March to May and September to November' },
  georgia: { from: 'Tbilisi', km: 0, bus: 0, train: 0, flight: 9, gateway: 'Tbilisi via Dubai, Doha or Sharjah (8 to 10 h with the stop)', legs: [['Tbilisi', 'Kazbegi', 155, 3.5, 'Georgian military road, Gudauri'], ['Kazbegi', 'Tbilisi', 155, 3.5, ''], ['Tbilisi', 'Kakheti (Sighnaghi)', 110, 2, 'wine region'], ['Tbilisi', 'Mtskheta', 25, 0.5, '']], hills: true, plan: 'Tbilisi base, Kazbegi overnight, Kakheti day, Mtskheta half day', hazards: ['Gudauri pass closes in snow; chains in winter'], season: 'May to October; ski December to March' },
  kazakhstan: { from: 'Almaty', km: 0, bus: 0, train: 0, flight: 3.5, gateway: 'Almaty via Delhi (3.5 h)', legs: [['Almaty', 'Charyn canyon', 200, 3.5, ''], ['Charyn', 'Kolsai lakes', 110, 2.5, 'night at Saty'], ['Kolsai', 'Almaty', 300, 5, ''], ['Almaty', 'Shymbulak', 25, 1, 'cable car']], plan: 'Almaty two nights, Charyn and Kolsai with a village night, Shymbulak day', hazards: ['Kolsai road unpaved after rain'], season: 'May to September' },
  maldives: { from: 'Male', km: 0, bus: 0, train: 0, flight: 3, gateway: 'Male via Mumbai or Bangalore', legs: [['Male airport', 'Maafushi', 27, 0.5, 'speedboat'], ['Male airport', 'Resort island', 0, 0.75, 'speedboat or seaplane, resort arranges']], plan: 'Local island (Maafushi) for the budget batch, one resort day pass; speedboats pre-booked', hazards: ['Seaplanes stop at sunset; late flights need a Male night'], season: 'November to April' },
  kenya: { from: 'Nairobi', km: 0, bus: 0, train: 0, flight: 6, gateway: 'Nairobi via Mumbai (6 h)', legs: [['Nairobi', 'Masai Mara', 270, 6, 'last 80 km rough'], ['Masai Mara', 'Lake Naivasha', 220, 5, ''], ['Naivasha', 'Nairobi', 90, 2, '']], plan: 'Mara three nights in a 4x4 van, Naivasha boat, Nairobi giraffe centre', hazards: ['Mara road after rain doubles the time'], season: 'July to October migration; January to February dry' },
  egypt: { from: 'Cairo', km: 0, bus: 0, train: 0, flight: 7, gateway: 'Cairo via Dubai or Doha', legs: [['Cairo', 'Giza', 20, 1, ''], ['Cairo', 'Luxor', 0, 1, 'flight or 10 h train'], ['Luxor', 'Aswan', 220, 4, 'or Nile cruise 3 nights'], ['Aswan', 'Abu Simbel', 280, 3.5, 'day trip, leave 4 am']], plan: 'Cairo two nights, fly to Luxor, Nile cruise to Aswan, Abu Simbel dawn trip', hazards: ['Heat May to September'], season: 'October to April' },
  turkey: { from: 'Istanbul', km: 0, bus: 0, train: 0, flight: 8, gateway: 'Istanbul via Dubai or direct from Mumbai', legs: [['Istanbul', 'Cappadocia', 0, 1.3, 'flight to Kayseri'], ['Cappadocia', 'Pamukkale', 0, 1.2, 'flight to Denizli'], ['Pamukkale', 'Antalya', 240, 4, '']], plan: 'Istanbul three nights, Cappadocia two with the balloon, Pamukkale, Antalya coast', hazards: ['Balloons cancel in wind; keep two mornings'], season: 'April to June and September to October' },
  japan: { from: 'Tokyo', km: 0, bus: 0, train: 0, flight: 10, gateway: 'Tokyo via Delhi or Singapore', legs: [['Tokyo', 'Kyoto', 0, 2.25, 'shinkansen, JR pass'], ['Kyoto', 'Osaka', 0, 0.5, 'train'], ['Osaka', 'Nara', 0, 0.75, 'train']], plan: 'Trains for everything; the JR pass pays for itself on one Tokyo–Kyoto return', hazards: ['Cherry blossom week hotels book 6 months out'], season: 'Late March to April and October to November' },
  schengen: { from: 'Paris', km: 0, bus: 0, train: 0, flight: 10, gateway: 'Paris, Amsterdam or Zurich via Dubai, Doha or direct from Mumbai', legs: [['Paris', 'Amsterdam', 0, 3.3, 'Thalys train'], ['Amsterdam', 'Lucerne', 0, 8, 'train via Basel'], ['Lucerne', 'Interlaken', 0, 2, 'train'], ['Interlaken', 'Paris', 0, 5.5, 'train via Basel']], plan: 'Trains between cities, coach only for day trips; Swiss pass for the mountain days', hazards: ['Strikes announce 48 h ahead; keep the Eurail flexibility'], season: 'May to September; Christmas markets December' },
  australia: { from: 'Sydney', km: 0, bus: 0, train: 0, flight: 14, gateway: 'Sydney or Melbourne via Singapore (14 h with the stop)', legs: [['Sydney', 'Blue Mountains', 100, 2, ''], ['Sydney', 'Melbourne', 0, 1.5, 'flight'], ['Melbourne', 'Great Ocean Road (Twelve Apostles)', 280, 4.5, 'long day']], plan: 'Sydney four nights, fly to Melbourne for three, Great Ocean Road as one long day', hazards: ['Distances are long; one driver-rest per 4 hours by law'], season: 'October to April' },
};
const ALIASES = { leh: 'ladakh', nubra: 'ladakh', pangong: 'ladakh', kaza: 'spiti', chandratal: 'spiti', rann: 'kutch', bhuj: 'kutch', dhordo: 'kutch', 'mount abu': 'mountabu', abu: 'mountabu', somnath: 'dwarka', munnar: 'kerala', alleppey: 'kerala', kochi: 'kerala', shillong: 'meghalaya', cherrapunji: 'meghalaya', gangtok: 'sikkim', lachung: 'sikkim', 'port blair': 'andaman', havelock: 'andaman', gulmarg: 'kashmir', pahalgam: 'kashmir', srinagar: 'kashmir', madikeri: 'coorg', bangkok: 'thailand', phuket: 'thailand', pattaya: 'thailand', krabi: 'thailand', uae: 'dubai', 'abu dhabi': 'dubai', ubud: 'bali', indonesia: 'bali', hanoi: 'vietnam', 'da nang': 'vietnam', 'sri lanka': 'srilanka', colombo: 'srilanka', 'kuala lumpur': 'singapore', malaysia: 'singapore', kathmandu: 'nepal', pokhara: 'nepal', thimphu: 'bhutan', paro: 'bhutan', tbilisi: 'georgia', kazbegi: 'georgia', almaty: 'kazakhstan', male: 'maldives', nairobi: 'kenya', 'masai mara': 'kenya', cairo: 'egypt', luxor: 'egypt', istanbul: 'turkey', cappadocia: 'turkey', tokyo: 'japan', kyoto: 'japan', europe: 'schengen', paris: 'schengen', switzerland: 'schengen', amsterdam: 'schengen', sydney: 'australia', melbourne: 'australia' };

function route(name) { const q = String(name || '').toLowerCase().trim(); if (!q) return null; if (ROUTES[q]) return Object.assign({ key: q }, ROUTES[q]); for (const [a, k] of Object.entries(ALIASES)) if (new RegExp('(^|[^a-z])' + a + '(?![a-z])').test(q)) return Object.assign({ key: k }, ROUTES[k]); for (const k of Object.keys(ROUTES)) if (new RegExp('(^|[^a-z])' + k + '(?![a-z])').test(q)) return Object.assign({ key: k }, ROUTES[k]); return null; }
const hrs = (h) => h >= 1 ? `${Math.round(h * 2) / 2} h` : `${Math.round(h * 60)} min`;
/** One line for quotes and the pre-departure brief. */
function journey(name, { city } = {}) {
  const r = route(name); if (!r) return ''; const start = city || r.from;
  const road = r.km ? `${r.km.toLocaleString('en-IN')} km from ${r.from}` : ''; const modes = [r.bus ? `AC bus about ${hrs(r.bus)}` : '', r.train ? `train about ${hrs(r.train)}` : '', r.flight ? `flight about ${hrs(r.flight)}${r.km ? '' : ' from ' + (start === r.from ? 'Ahmedabad' : start)}` : ''].filter(Boolean).join(', ');
  return `${road ? road + '; ' : ''}${modes}. Gateway: ${r.gateway}. ${r.plan}.`;
}
/** Day-by-day legs with the halts the rules force. */
function legs(name) { const r = route(name); if (!r) return []; return r.legs.map(([a, b, km, h, note]) => ({ from: a, to: b, km, hours: h, note })); }
/** Audit a plan: list of {from, to, km, hours, altitude?} legs grouped per day, or a route key. Returns warnings. */
function check(planOrName, { month } = {}) {
  const r = typeof planOrName === 'string' ? route(planOrName) : null; const days = r ? groupByDay(r) : planOrName; const warnings = []; if (!days || !days.length) return warnings;
  const hills = r ? !!r.hills : days.some(d => d.hills);
  days.forEach((d, i) => { const km = d.reduce ? d.reduce((n, l) => n + (l.km || 0), 0) : d.km || 0; const h = d.reduce ? d.reduce((n, l) => n + (l.hours || 0), 0) : d.hours || 0; const cap = hills ? RULES.hillsKmPerDay : RULES.plainsKmPerDay;
    if (km > cap) warnings.push(`Day ${i + 1}: ${km} km is over the ${cap} km ${hills ? 'hill' : 'plains'} limit; split it or add a halt.`);
    if (h * (1 + RULES.bufferPerLegPct / 100) > 10 && hills) warnings.push(`Day ${i + 1}: about ${Math.round(h * 1.15)} h on hill roads with buffer; the bus would be driving after dark, which we do not do.`);
    if (h > RULES.driverRestHours * 2) warnings.push(`Day ${i + 1}: ${hrs(h)} of driving needs two rest stops (one every ${RULES.driverRestHours} h).`); });
  if (r && r.key === 'ladakh') warnings.push('Ladakh: keep 2 rest days in Leh before Khardung La; the plan above assumes them.');
  if (r && month && r.season && /monsoon|July to September|June to September/i.test(r.hazards.join(' ')) && [7, 8, 9].includes(month)) warnings.push(`${r.key}: monsoon month; ${r.hazards.find(x => /monsoon|July|August|September/i.test(x)) || 'ghat roads slow'}.`);
  if (r && r.key === 'spiti' && month && ![6, 7, 8, 9, 10].includes(month)) warnings.push('Spiti: Kunzum and the Manali side are closed outside June to October; the loop becomes an out-and-back from Shimla.');
  return warnings;
}
function groupByDay(r) { const days = []; let cur = [], km = 0, h = 0; const cap = r.hills ? RULES.hillsKmPerDay : RULES.plainsKmPerDay; for (const [a, b, lkm, lh, note] of r.legs) { if ((km + lkm > cap || h + lh > 9 || /night halt|sleep/.test(note)) && cur.length) { days.push(cur); cur = []; km = 0; h = 0; } cur.push({ from: a, to: b, km: lkm, hours: lh, note }); km += lkm; h += lh; } if (cur.length) days.push(cur); return days; }
/** Chief-facing card. */
function card(name, { city } = {}) {
  const r = route(name); if (!r) return `No route for "${name}" in the desk yet; tell me the destination and the gateway and I will add it.`;
  const days = groupByDay(r); const w = check(r.key);
  return [`${r.key.charAt(0).toUpperCase() + r.key.slice(1)}: ${journey(name, { city })}`, 'Legs: ' + r.legs.map(([a, b, km, h, note]) => `${a} → ${b} ${km ? km + ' km, ' : ''}${hrs(h)}${note ? ' (' + note + ')' : ''}`).join('; ') + '.', `Driving days by the rules (${r.hills ? RULES.hillsKmPerDay + ' km hill' : RULES.plainsKmPerDay + ' km plains'} limit, rest every ${RULES.driverRestHours} h, no night driving in the hills): ${days.map((d, i) => `Day ${i + 1} ${d[0].from} → ${d[d.length - 1].to} (${d.reduce((n, l) => n + l.km, 0)} km, ${hrs(d.reduce((n, l) => n + l.hours, 0))})`).join('; ')}.`, r.hazards.length ? `Watch: ${r.hazards.join('; ')}.` : '', `Season: ${r.season}.`, w.length ? `Checks: ${w.join(' ')}` : ''].filter(Boolean).join('\n');
}
function mentions(text) { return /\b(route|routing|how (do|will|to) (we |you )?(reach|get|travel|go)|how (long|many hours|far)|drive time|driving|kitne ghante|kitna time|kaise (jayenge|pahunch\w*|jaate)|road (from|to|condition)|by road|by bus|by train|train se|bus se|flight se|journey|halt|night halt|km\b|kilomet\w*|distance|highway|ghat|pass (open|closed)|road (open|closed))\b/i.test(String(text || '')); }
module.exports = { ROUTES, RULES, ALIASES, route, journey, legs, check, card, mentions, groupByDay };
