'use strict';
/**
 * universe.js — every customer a travel company can face, generated by combination, each with a psyche, and
 * played against OYE so it learns to handle them before it meets them for real.
 *
 * A persona = life stage × geography × income × occasion × group × psyche (decision style, risk attitude, price
 * sensitivity, trust, communication style, control need) × language × channel × mood. The behaviour model turns a
 * persona into a conversation: how they open, what they ask (driven by fears and style), how they react to a reply
 * (price shown, question ignored, scarcity, proof, hold offered), and when they book, stall, or leave.
 *
 * Scenarios: sales enquiry, support complaint, marketing broadcast reaction, probing (a vague lead that must be
 * qualified). A judge scores each conversation; the playbook aggregates what works for whom and teaches the mind.
 */
const DIMS = {
  lifeStage: ['student', 'young professional', 'newly married', 'parent of young kids', 'parent of teens', 'single mid-career', 'empty nester', 'retired'],
  geo: ['tier-1 metro', 'tier-2 city', 'tier-3 town', 'NRI in the Gulf', 'NRI in the West', 'foreign tourist'],
  income: ['tight', 'middle', 'comfortable', 'affluent'],
  occasion: ['weekend escape', 'long vacation', 'honeymoon', 'family reunion', 'corporate offsite', 'college trip', 'pilgrimage', 'adventure', 'workation', 'birthday or anniversary', 'bachelor trip'],
  group: ['solo', 'couple', 'small friends group', 'large friends group', 'family with kids', 'family with seniors', 'colleagues', 'women only'],
  decision: ['impulsive', 'analytical', 'consensus seeker', 'defers to spouse or parent'],
  risk: ['anxious', 'cautious', 'bold'],
  price: ['very price sensitive', 'value seeker', 'price insensitive'],
  trust: ['skeptical', 'neutral', 'trusting'],
  style: ['terse', 'chatty', 'formal', 'emoji and slang'],
  control: ['wants control of every detail', 'wants it all handled'],
  language: ['english', 'hinglish', 'hindi script', 'gujarati script'],
  channel: ['whatsapp', 'website chat', 'instagram dm'],
  mood: ['curious', 'rushed', 'anxious', 'bargaining', 'confused', 'angry'],
};
const SCENARIOS = ['sales', 'support', 'marketing', 'probing'];
const ALL = Object.values(DIMS).reduce((n, v) => n * v.length, 1); // size of the full space

let seed = 11; const rnd = () => (seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff; const pick = (a) => a[Math.floor(rnd() * a.length)];
function setSeed(s) { seed = s; }

/** Stratified sample: cycles every value of every dimension so coverage is complete, then randomises the rest. */
function generate(n = 500) {
  const keys = Object.keys(DIMS); const out = [];
  for (let i = 0; i < n; i++) {
    const p = {}; for (const k of keys) p[k] = i < DIMS[k].length * 2 ? DIMS[k][i % DIMS[k].length] : pick(DIMS[k]);
    // Coherence: a few combinations do not occur; nudge them.
    if (p.lifeStage === 'student') { p.income = pick(['tight', 'middle']); if (!/college|weekend|adventure|bachelor/.test(p.occasion)) p.occasion = pick(['college trip', 'weekend escape', 'adventure']); }
    if (p.occasion === 'honeymoon') { p.group = 'couple'; p.lifeStage = 'newly married'; }
    if (p.occasion === 'college trip') { p.group = 'large friends group'; p.lifeStage = 'student'; }
    if (p.occasion === 'corporate offsite') p.group = 'colleagues';
    if (p.group === 'family with kids') p.lifeStage = pick(['parent of young kids', 'parent of teens']);
    if (p.lifeStage === 'retired') { p.occasion = pick(['pilgrimage', 'long vacation', 'family reunion']); p.style = pick(['formal', 'chatty']); }
    if (p.geo === 'foreign tourist') p.language = 'english';
    if (p.geo === 'tier-3 town' && p.language === 'english') p.language = pick(['hinglish', 'hindi script', 'gujarati script']);
    if (p.mood === 'angry') p.scenario = 'support'; else p.scenario = pick(SCENARIOS.filter(s => s !== 'support'));
    p.id = 'u' + i; p.name = pick(['Riya', 'Amit', 'Priya', 'Rahul', 'Sneha', 'Karan', 'Meera', 'Vikram', 'Pooja', 'Arjun', 'Neha', 'Dev', 'Kavya', 'Rohan', 'Anjali', 'Sameer']);
    p.n = p.group === 'solo' ? 1 : p.group === 'couple' ? 2 : p.group === 'small friends group' ? 3 + Math.floor(rnd() * 3) : p.group === 'large friends group' ? 6 + Math.floor(rnd() * 10) : p.group === 'colleagues' ? 8 + Math.floor(rnd() * 20) : 3 + Math.floor(rnd() * 4);
    out.push(p);
  }
  return out;
}

const HI = (p) => p.language !== 'english';
const t = (p, en, hi, dev, guj) => p.language === 'hindi script' ? (dev || hi) : p.language === 'gujarati script' ? (guj || dev || hi) : HI(p) ? hi : en;
/** What this persona says first, and what it will ask before it decides. */
function script(p, trip) {
  const name = trip.name; const nameHi = { Goa: 'गोवा', Manali: 'मनाली' }[name] || name; const nameGu = { Goa: 'ગોવા', Manali: 'મનાલી' }[name] || name;
  const openers = {
    sales: [t(p, `hi, ${p.n} of us planning ${name.toLowerCase()} for a ${p.occasion}, is it available?`, `bhai ${name.toLowerCase()} ka plan hai ${p.n} log, ${p.occasion} ke liye, available hai?`, `${nameHi} ${p.n} लोगों के लिए, ${p.occasion}, क्या उपलब्ध है?`, `${nameGu} ${p.n} લોકો માટે, ${p.occasion}, ઉપલબ્ધ છે?`)],
    probing: [t(p, 'hi', 'hello', 'नमस्ते', 'નમસ્તે'), t(p, 'need some info', 'kuch info chahiye', 'जानकारी चाहिए', 'માહિતી જોઈએ છે'), t(p, 'trip?', 'trip ka kya hai?', 'ट्रिप?', 'ટ્રિપ?')],
    marketing: [t(p, 'PLAN', 'PLAN', 'PLAN', 'PLAN')],
    support: [t(p, `this is not what was promised, the ${pick(['bus was 3 hours late', 'hotel was nothing like the photos', 'captain was rude', 'room was dirty', 'food was cold every day'])}. i want a refund`, `yeh promise nahi tha, ${pick(['bus 3 ghante late thi', 'hotel photo jaisa bilkul nahi tha', 'captain rude tha', 'room ganda tha'])}. refund chahiye`, `यह वादा नहीं था, बस 3 घंटे लेट थी। रिफंड चाहिए`, `આ વચન નહોતું, બસ 3 કલાક મોડી હતી. રિફંડ જોઈએ`)],
  };
  // Questions driven by psyche. Order matters: fears first.
  const q = [];
  if (p.risk === 'anxious' || /family|women|seniors/.test(p.group)) q.push(t(p, 'is it safe? any issues before?', 'safe hai? pehle koi problem hui?', 'सुरक्षित है?', 'સુરક્ષિત છે?'));
  if (p.trust === 'skeptical') q.push(t(p, 'do you have reviews or proof from past trips?', 'koi reviews ya proof hai pichle trips ka?', 'कोई रिव्यू है?', 'કોઈ રિવ્યુ છે?'));
  if (p.decision === 'analytical' || p.control.startsWith('wants control')) q.push(t(p, 'what exactly is included and what is not?', 'kya kya included hai aur kya nahi?', 'क्या शामिल है?', 'શું સમાવેશ છે?'));
  if (p.risk !== 'bold') q.push(t(p, 'what if we have to cancel?', 'cancel karna pade to?', 'रद्द करना पड़े तो?', 'રદ કરવું પડે તો?'));
  if (/kids|seniors/.test(p.group)) q.push(t(p, `is it ok for ${p.group.includes('kids') ? 'kids aged 6 and 9' : 'my parents aged 68'}?`, `${p.group.includes('kids') ? '6 aur 9 saal ke bachche' : '68 saal ke parents'} ke liye theek hai?`, 'बच्चों के लिए ठीक है?', 'બાળકો માટે ઠીક છે?'));
  if (/pilgrimage|family/.test(p.occasion) || p.lifeStage === 'retired') q.push(t(p, 'veg food available?', 'veg khana milega?', 'शाकाहारी खाना?', 'શાકાહારી જમવાનું?'));
  if (p.price === 'very price sensitive') q.push(t(p, 'any discount for ' + p.n + '?', p.n + ' logon ke liye discount?', 'डिस्काउंट?', 'ડિસ્કાઉન્ટ?'));
  if (p.decision === 'consensus seeker') q.push(t(p, 'ok let me check with the group and get back', 'group se pooch ke batata hoon', 'ग्रुप से पूछ के बताता हूँ', 'ગ્રુપ ને પૂછી ને કહું'));
  if (p.decision === 'defers to spouse or parent') q.push(t(p, 'i need to ask my wife', 'wife se poochna padega', 'पत्नी से पूछना पड़ेगा', 'પત્ની ને પૂછવું પડશે'));
  if (p.control === 'wants it all handled') q.push(t(p, 'can you just handle everything? pickup to drop', 'sab aap handle kar loge? pickup se drop tak', 'सब आप संभाल लोगे?', 'બધું તમે સંભાળી લેશો?'));
  return { opener: openers[p.scenario], questions: q.slice(0, p.style === 'terse' ? 2 : 4) };
}

/** How the persona reacts to a reply. Returns the next message or null when the conversation is over, plus a verdict flag. */
function react(p, reply, state) {
  const r = String(reply || '').toLowerCase(); const hasPrice = /₹|per person/.test(r); const asksHold = /hold/.test(r); const proof = /review|captain|travelled|batch|traveller|women/.test(r);
  if (p.scenario === 'support') { state.handled = /founder|24|call|sorry|serious|समझ|samajh|ગંભીર/.test(r) && !/hold|advance|seat/.test(r); return null; }
  if (p.scenario === 'marketing') { state.replied = true; return null; }
  if (state.pendingQuestion && !state.answered) { const key = state.pendingQuestion; const ok = ({ safe: /captain|women|safe|emergency|ladkiyon|सुरक्षित|કેપ્ટન/, proof: /review|traveller|batch|photo|proof/, included: /included|stay|meals|khana/, cancel: /transfer|refund|cancel/, kids: /family|parents|welcome|kids|relaxed|20/, veg: /veg|jain/, discount: /inclusive|separately|organiser|balance|fixed/, group: /time|hold|seats|sochiye/, wife: /time|hold|seats|sochiye/, handle: /captain|handle|included|sab/ })[key]; state.answered = ok ? ok.test(r) : true; if (!state.answered) { state.ignored++; if (state.ignored >= 2) return null; return state.repeat; } }
  if (hasPrice && p.price === 'very price sensitive' && !state.objected) { state.objected = true; return p.language === 'english' ? 'too expensive, any discount?' : 'mehenga hai, discount?'; }
  if (asksHold && !state.decided) {
    const willing = (p.decision === 'impulsive' ? 0.9 : p.decision === 'analytical' ? 0.6 : 0.4) + (p.trust === 'trusting' ? 0.2 : p.trust === 'skeptical' ? (proof ? 0.1 : -0.3) : 0) + (p.mood === 'rushed' ? 0.2 : 0) - (p.price === 'very price sensitive' ? 0.2 : 0);
    state.decided = true; if (willing >= 0.6) { state.booked = true; return p.language === 'english' ? 'ok hold ' + p.n + (p.n > 1 ? ' seats' : ' seat') : 'hold karo ' + p.n; }
    return p.language === 'english' ? 'will think and tell you' : 'soch ke batata hoon';
  }
  return null;
}

/** Play one persona against the WhatsApp agent. Returns the transcript and a verdict. */
async function play(p, growth, trip) {
  const sc = script(p, trip); const id = 'universe-' + p.id + '-' + Date.now().toString(36); const log = []; const state = { ignored: 0 };
  const send = async (text) => { const r = await growth.chat({ id, name: p.name, text, source: 'universe' }); log.push({ who: 'customer', text }, { who: 'atlas', text: r.reply, intent: r.intent, handoff: r.handoff }); return r; };
  let r; for (const o of sc.opener) r = await send(o);
  let next = react(p, r.reply, state);
  const keyOf = (q) => /safe|सुरक्षित|સુરક્ષિત/.test(q) ? 'safe' : /review|proof|रिव्यू|રિવ્યુ/.test(q) ? 'proof' : /included|शामिल|સમાવેશ/.test(q) ? 'included' : /cancel|रद्द|રદ/.test(q) ? 'cancel' : /kids|parents|बच्च|બાળ/.test(q) ? 'kids' : /veg|शाकाहारी|શાકાહારી/.test(q) ? 'veg' : /discount|डिस्काउंट|ડિસ્કાઉન્ટ/.test(q) ? 'discount' : /group|ग्रुप|ગ્રુપ/.test(q) ? 'group' : /wife|पत्नी|પત્ની/.test(q) ? 'wife' : 'handle';
  const qs = sc.questions.slice(); let turns = 0;
  while (turns++ < 8 && p.scenario !== 'support' && p.scenario !== 'marketing') {
    if (next) { r = await send(next); next = react(p, r.reply, state); continue; }
    const q = qs.shift(); if (!q) break;
    state.pendingQuestion = keyOf(q); state.answered = false; state.repeat = q;
    r = await send(q); next = react(p, r.reply, state);
    if (state.ignored >= 2) break;
  }
  if (!next && !state.decided && p.scenario === 'sales' && qs.length === 0 && state.ignored < 2) { r = await send(p.language === 'english' ? 'ok' : 'theek hai'); next = react(p, r.reply, state); if (next) { r = await send(next); } }
  const verdict = judge(p, log, state);
  return { persona: p, log, state, verdict };
}
function judge(p, log, state) {
  const atlas = log.filter(x => x.who === 'atlas'); const last = atlas[atlas.length - 1] || {};
  if (p.scenario === 'support') return { ok: !!state.handled, reason: state.handled ? 'complaint acknowledged, escalated, no pitch' : 'complaint not handled: must acknowledge, promise the founder call, and never pitch' };
  if (p.scenario === 'marketing') return { ok: /D1|plan|per person/i.test(last.text || ''), reason: 'PLAN reply should get the plan and price' };
  if (p.scenario === 'probing') { const asked = atlas.some(a => /which trip|dates|how many|kaunsa|kitne|कौन|કયો|કેટલા/i.test(a.text)); return { ok: asked, reason: asked ? 'qualified the vague lead' : 'did not ask trip, dates and group size' }; }
  if (state.ignored >= 2) return { ok: false, reason: 'ignored the question: ' + state.pendingQuestion };
  if (state.booked) return { ok: true, reason: 'booked' };
  if (state.decided) return { ok: true, reason: 'stalled politely (' + p.decision + ')', soft: true };
  return { ok: false, reason: 'never reached a hold offer' };
}

/** Aggregate what works for whom; produce lessons the mind can memorise. */
function playbook(results) {
  const by = {}; const add = (k, v, ok) => { const b = by[k] = by[k] || {}; const c = b[v] = b[v] || { n: 0, ok: 0 }; c.n++; if (ok) c.ok++; };
  const fails = {};
  for (const r of results) { for (const k of Object.keys(DIMS)) add(k, r.persona[k], r.verdict.ok); add('scenario', r.persona.scenario, r.verdict.ok); if (!r.verdict.ok) fails[r.verdict.reason] = (fails[r.verdict.reason] || 0) + 1; }
  const table = Object.fromEntries(Object.entries(by).map(([k, v]) => [k, Object.entries(v).map(([val, c]) => ({ value: val, n: c.n, rate: +(c.ok / c.n).toFixed(2) })).sort((a, b) => a.rate - b.rate)]));
  const lessons = [];
  for (const [k, rows] of Object.entries(table)) { const worst = rows[0], best = rows[rows.length - 1]; if (worst && best && best.rate - worst.rate >= 0.15) lessons.push(`${capital(worst.value)} customers convert at ${Math.round(worst.rate * 100)} percent while ${best.value} customers convert at ${Math.round(best.rate * 100)} percent.`); }
  const TIPS = { anxious: 'Anxious customers need safety proof before any price.', skeptical: 'Skeptical customers need reviews and real photos before a hold is offered.', 'consensus seeker': 'Consensus seekers need a shareable one-page plan and a 24 hour hold without advance.', 'defers to spouse or parent': 'Customers who defer to a spouse need a message they can forward as is.', 'very price sensitive': 'Very price sensitive customers need the all-inclusive comparison and a pay-in-parts option.', 'wants it all handled': 'Customers who want it all handled need one sentence promising pickup to drop.', terse: 'Terse customers need replies under 40 words.', chatty: 'Chatty customers accept longer replies but still need one next step.', 'family with kids': 'Families with kids ask about safety, food and pace before price.', 'family with seniors': 'Families with seniors need altitude, walking and doctor answers.', 'women only': 'Women-only groups need the female rooming and captain line first.', impulsive: 'Impulsive customers should be offered the hold in the first reply.', analytical: 'Analytical customers need the inclusions list and the day-wise plan before the hold.', angry: 'Angry customers must never be pitched; acknowledge, escalate to the founder, promise a call time.' };
  for (const [k, tip] of Object.entries(TIPS)) if (results.some(r => Object.values(r.persona).includes(k))) lessons.push(tip);
  return { table, fails: Object.entries(fails).sort((a, b) => b[1] - a[1]).map(([reason, n]) => ({ reason, n })), lessons, total: results.length, ok: results.filter(r => r.verdict.ok).length };
}
const capital = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/** Read a real customer message and guess the psyche cues that matter for the reply. */
function detect(text) {
  const t = String(text).toLowerCase(); const traits = [];
  if (/safe|safety|secure|alone|akeli|girls|women|ladies|सुरक्षित|સુરક્ષિત/.test(t)) traits.push('anxious');
  if (/review|proof|genuine|fraud|scam|legit|real|trust|photos of/.test(t)) traits.push('skeptical');
  if (/exactly|detail|itinerary|include|breakdown|day wise|schedule/.test(t)) traits.push('analytical');
  if (/group|friends|everyone|sabko|discuss|check with|poochh?|पूछ|પૂછ/.test(t)) traits.push('consensus seeker');
  if (/wife|husband|parents|papa|mummy|dad|mom/.test(t) && /ask|pooch|पूछ|પૂછ|permission/.test(t)) traits.push('defers to spouse or parent');
  if (/cheap|cheapest|discount|budget|expensive|mehenga|kam|सस्ता|સસ્તું/.test(t)) traits.push('very price sensitive');
  if (/handle|manage|sab|everything|take care|arrange/.test(t)) traits.push('wants it all handled');
  if (/urgent|asap|today|abhi|jaldi|tomorrow|kal/.test(t)) traits.push('rushed');
  if (/kids?|children|bachch|बच्च|બાળ/.test(t)) traits.push('family with kids');
  if (/parents|senior|elderly|68|65|70 year/.test(t)) traits.push('family with seniors');
  if (t.split(/\s+/).length <= 4) traits.push('terse');
  return traits;
}
module.exports = { DIMS, SCENARIOS, ALL, generate, script, react, play, judge, playbook, detect, setSeed };
