'use strict';
/**
 * visa.js — the visa and permits desk: its own knowledge base and its own case file.
 *
 * Knowledge: what an Indian passport holder needs for every destination the clan sells (visa-free, visa on arrival,
 * e-visa, embassy visa, conditional), plus the domestic permits (inner line, protected area, entry permits), with fee,
 * processing time, stay, documents, the official link and the traps that get people refused at the counter.
 * Rules change: every entry carries the month it was checked and the official URL to verify before a batch.
 *
 * Cases: one row per traveller per trip (status, documents ticked, applied and decision dates, notes), saved in
 * visa.json next to the mind. due() turns trip dates into deadlines the autopilot and the trip board act on.
 *
 * Connections: the WhatsApp agent (faq:visa), the chief agent (visa tool and fallback), the council (visa agent),
 * the autopilot (visa_apply proposals), the trip board (flags), the pre-departure brief, and the dashboard desk.
 */
const fs = require('fs');
const path = require('path');
const DEST = require('./destinations');

const CHECKED = '2026-06';
const BASE = ['Passport valid 6 months beyond the return date, 2 blank pages', 'Return or onward ticket', 'Hotel confirmation for every night (we send the group booking)', 'Proof of funds: bank statement of the last 3 months (₹50,000+ balance is comfortable)', 'Travel insurance (recommended; mandatory where marked)'];
const EVISA = ['Passport bio page scan (colour, all four corners)', 'Photo 35×45 mm, white background, taken in the last 6 months, no glasses', 'Working email and a debit or credit card for the fee'];
const EMBASSY = ['Cover letter with the day-by-day itinerary (we write it)', 'Flight and hotel bookings', 'Bank statement, last 6 months, stamped', 'Income tax returns for the last 2 to 3 years', 'Employment letter or business proof (GST, shop act, visiting card)', 'Travel insurance for the whole stay', 'Biometrics appointment at the visa centre (in person)'];

// type: free (nothing before flying), card (free, online arrival card), voa (pay at the airport), evisa, eta (online
// authorisation), embassy (sticker visa, apply in person), conditional (e-visa only with another valid visa), none
// (domestic), permit (domestic permit). fee in INR (approximate), days = working days to process, buffer = extra days we keep.
const KB = {
  thailand: { country: 'Thailand', type: 'card', stay: '60 days', fee: 0, feeNote: 'free', days: 0, buffer: 3, apply: 'Thailand Digital Arrival Card (TDAC) online within 3 days before the flight', url: 'https://tdac.immigration.go.th', docs: BASE, extras: ['TDAC confirmation (screenshot) for every traveller', 'Cash or card proof of about 20,000 THB per person can be asked at the counter'], tips: ['Visa-free entry is for tourism only; no work', 'Keep the hotel address handy for the TDAC form'] },
  malaysia: { country: 'Malaysia', type: 'card', stay: '30 days', fee: 0, feeNote: 'free', days: 0, buffer: 3, apply: 'Malaysia Digital Arrival Card (MDAC) online within 3 days before the flight', url: 'https://imigresen-online.imigresen.gov.my/mdac/main', docs: BASE, extras: ['MDAC confirmation for every traveller'], tips: ['Visa-free stay for Indians runs to the end of 2026; verify before each batch'] },
  srilanka: { country: 'Sri Lanka', type: 'eta', stay: '30 days', fee: 0, feeNote: 'free ETA for Indian passports', days: 1, buffer: 4, apply: 'Electronic Travel Authorisation online, approved in a day', url: 'https://www.eta.gov.lk', docs: BASE, extras: ['ETA approval email (print or screenshot)'], tips: ['Apply only on the official site; copycat sites charge USD 50 for nothing'] },
  vietnam: { country: 'Vietnam', type: 'evisa', stay: '90 days', fee: 2100, feeNote: 'USD 25 single entry', days: 5, buffer: 7, apply: 'e-visa online, 3 to 5 working days', url: 'https://evisa.gov.vn', docs: BASE.concat(EVISA), extras: ['Printed e-visa for every traveller', 'Entry airport must match the one on the e-visa'], tips: ['Name, passport number and date of birth must match the passport exactly; one typo means a new application'] },
  indonesia: { country: 'Indonesia', type: 'voa', stay: '30 days, extendable once', fee: 2700, feeNote: 'IDR 500,000 visa on arrival (e-VoA online saves the queue)', days: 2, buffer: 5, apply: 'e-VoA online before flying, or pay at the airport; All Indonesia arrival declaration online within 3 days before', url: 'https://evisa.imigrasi.go.id', docs: BASE, extras: ['Bali tourist levy IDR 150,000 per person (lovebali.baliprov.go.id), pay online before landing', 'All Indonesia arrival declaration QR code'], tips: ['Return ticket is checked at the VoA counter', 'Carry a card for the VoA; cash queues are long'] },
  singapore: { country: 'Singapore', type: 'embassy', stay: '30 days per visit (visa usually multiple entry, valid up to 2 years)', fee: 1900, feeNote: 'SGD 30 plus the authorised agent fee of about ₹500 to ₹1,000', days: 5, buffer: 10, apply: 'through an ICA authorised visa agent or the High Commission, 3 to 5 working days; SG Arrival Card online within 3 days before the flight', url: 'https://www.ica.gov.sg', docs: BASE.concat(EVISA, ['Form 14A', 'Cover letter from us']), extras: ['SG Arrival Card for every traveller (free)'], tips: ['Apply 3 weeks before the batch; agents do not refund on refusal'] },
  maldives: { country: 'Maldives', type: 'card', stay: '30 days', fee: 0, feeNote: 'free visa on arrival', days: 0, buffer: 4, apply: 'Traveller declaration (IMUGA) online within 96 hours before the flight', url: 'https://imuga.immigration.gov.mv', docs: BASE, extras: ['IMUGA declaration QR for every traveller'], tips: ['Resort or hotel confirmation is checked; keep the voucher ready'] },
  nepal: { country: 'Nepal', type: 'free', stay: 'no limit for tourism', fee: 0, feeNote: 'no visa for Indian citizens', days: 0, buffer: 0, apply: 'nothing; carry an accepted ID', url: 'https://www.immigration.gov.np', docs: ['Passport, or voter ID card (original)', 'Aadhaar accepted only for travellers under 15 and over 65', 'Kids: school ID or birth certificate with a parent'], extras: [], tips: ['Aadhaar alone is not accepted at the airport for adults; carry passport or voter ID'] },
  bhutan: { country: 'Bhutan', type: 'permit', stay: 'as per permit', fee: 1200, feeNote: '₹1,200 per person per day sustainable development fee; kids under 6 free, 6 to 12 half', days: 1, buffer: 7, apply: 'entry permit online or at Phuentsholing or Paro immigration', url: 'https://visit.doi.gov.bt', docs: ['Passport, or voter ID card (original)', 'Hotel confirmation', 'Two passport photos per person', 'Kids: birth certificate or school ID'], extras: ['Permit extension needed beyond Thimphu and Paro (we arrange it)'], tips: ['The daily fee is per night in Bhutan; it is in our price where the plan says so'] },
  uae: { country: 'UAE', type: 'embassy', stay: '30 days (14 and 60 day visas also exist)', fee: 7000, feeNote: 'about ₹6,500 to ₹8,000 for 30 days through the airline, hotel or an agent', days: 4, buffer: 10, apply: 'online through the airline (Emirates, flydubai, Air Arabia), the hotel or an approved agent, 3 to 5 working days', url: 'https://u.ae/en/information-and-services/visa-and-emirates-id/do-you-need-an-entry-permit-or-a-visa-to-enter-the-uae', docs: BASE.concat(EVISA, ['PAN card copy (some agents ask)']), extras: ['Visa on arrival instead for Indians holding a valid US visa or green card, or a UK or EU residence permit'], tips: ['Apply 10 days before the batch; last-minute visas cost double', 'Overstay fines are per day; return on the booked flight'] },
  georgia: { country: 'Georgia', type: 'evisa', stay: '30 days', fee: 1700, feeNote: 'USD 20', days: 5, buffer: 7, apply: 'e-visa online, 5 working days', url: 'https://www.evisa.gov.ge', docs: BASE.concat(EVISA), extras: ['Visa-free instead for Indians holding a valid US, UK, Schengen or GCC visa or residence'], tips: ['No visa on arrival for Indian passports; do not fly without the e-visa'] },
  kazakhstan: { country: 'Kazakhstan', type: 'free', stay: '14 days', fee: 0, feeNote: 'visa-free for Indian passports', days: 0, buffer: 0, apply: 'nothing before flying', url: 'https://www.gov.kz/memleket/entities/mfa', docs: BASE, extras: [], tips: ['14 days exactly; a longer plan needs an e-visa'] },
  azerbaijan: { country: 'Azerbaijan', type: 'evisa', stay: '30 days', fee: 2200, feeNote: 'USD 26 (3 working days) or USD 61 urgent (3 hours)', days: 3, buffer: 5, apply: 'ASAN e-visa online', url: 'https://evisa.gov.az', docs: BASE.concat(EVISA), extras: [], tips: ['Print the e-visa; it is checked at boarding in India'] },
  armenia: { country: 'Armenia', type: 'evisa', stay: '21 days (USD 7) or 120 days (USD 31)', fee: 600, feeNote: 'USD 7 for 21 days', days: 3, buffer: 5, apply: 'e-visa online, or visa on arrival at Yerevan', url: 'https://evisa.mfa.am', docs: BASE.concat(EVISA), extras: [], tips: ['Apply online; the arrival queue takes an hour'] },
  uzbekistan: { country: 'Uzbekistan', type: 'evisa', stay: '30 days', fee: 1700, feeNote: 'USD 20', days: 3, buffer: 5, apply: 'e-visa online, 2 to 3 working days', url: 'https://e-visa.gov.uz', docs: BASE.concat(EVISA), extras: ['Hotel registration slips are collected on exit; keep every one'], tips: ['Register at every hotel; the slips are checked when you leave'] },
  turkey: { country: 'Turkey', type: 'conditional', stay: '30 days', fee: 4300, feeNote: 'e-visa about USD 50 only for Indians holding a valid Schengen, US, UK or Ireland visa or residence; otherwise a sticker visa at the consulate, about ₹6,000 plus centre fees', days: 12, buffer: 10, apply: 'e-visa online if you qualify, else the Turkish visa application centre, 10 to 15 working days', url: 'https://www.evisa.gov.tr', docs: BASE.concat(EMBASSY), extras: [], tips: ['Check the condition first; most group travellers need the sticker visa, so start 5 weeks out'] },
  egypt: { country: 'Egypt', type: 'conditional', stay: '30 days', fee: 2100, feeNote: 'e-visa USD 25 for Indians holding a valid US, UK, Schengen, Canada, Australia, NZ or Japan visa; otherwise embassy visa about ₹2,500', days: 7, buffer: 10, apply: 'e-visa online if you qualify, else the Egyptian embassy or consulate, 7 to 10 working days', url: 'https://visa2egypt.gov.eg', docs: BASE.concat(EMBASSY), extras: [], tips: ['Group letters from us speed up the embassy route'] },
  oman: { country: 'Oman', type: 'conditional', stay: '14 days visa-free with a qualifying visa, else 30 days on an e-visa', fee: 4500, feeNote: 'free for 14 days if holding a valid US, UK, Schengen, Canada, Australia or Japan visa or a GCC residence; otherwise e-visa about OMR 20', days: 4, buffer: 7, apply: 'Royal Oman Police e-visa portal', url: 'https://evisa.rop.gov.om', docs: BASE.concat(EVISA), extras: [], tips: ['Hotel booking and return ticket are mandatory on the e-visa form'] },
  kenya: { country: 'Kenya', type: 'eta', stay: '90 days', fee: 2800, feeNote: 'USD 30 to 34 eTA', days: 3, buffer: 7, apply: 'Kenya eTA online, up to 3 working days', url: 'https://www.etakenya.go.ke', docs: BASE.concat(EVISA), extras: ['Yellow fever certificate only if arriving from an endemic country (not India)'], tips: ['Apply at least a week before; weekends do not count'] },
  mauritius: { country: 'Mauritius', type: 'card', stay: '60 days', fee: 0, feeNote: 'free entry for Indian passports', days: 0, buffer: 3, apply: 'All-in-one travel digital form online before the flight', url: 'https://safemauritius.govmu.org', docs: BASE, extras: ['Funds of about USD 100 per day can be asked'], tips: ['Hotel confirmation must show every night'] },
  seychelles: { country: 'Seychelles', type: 'eta', stay: '30 days', fee: 900, feeNote: 'EUR 10 travel authorisation', days: 1, buffer: 4, apply: 'Seychelles Electronic Border System, within 30 days before the flight', url: 'https://seychelles.govtas.com', docs: BASE, extras: [], tips: ['Yacht or hotel booking is uploaded on the form'] },
  hongkong: { country: 'Hong Kong', type: 'eta', stay: '14 days', fee: 0, feeNote: 'free pre-arrival registration', days: 1, buffer: 4, apply: 'Pre-Arrival Registration online (valid 6 months)', url: 'https://www.immd.gov.hk/eng/services/visas/pre-arrival_registration_for_indian_nationals.html', docs: BASE, extras: ['Printed PAR slip for every traveller'], tips: ['Registration is free; agents charging for it add nothing'] },
  cambodia: { country: 'Cambodia', type: 'evisa', stay: '30 days', fee: 3000, feeNote: 'USD 30 plus USD 6 processing; visa on arrival USD 30', days: 3, buffer: 5, apply: 'e-visa online or visa on arrival at Siem Reap and Phnom Penh', url: 'https://www.evisa.gov.kh', docs: BASE.concat(EVISA), extras: [], tips: ['e-visa is valid only at the listed entry points'] },
  philippines: { country: 'Philippines', type: 'card', stay: '14 days visa-free (30 days with a valid US, Japan, Australia, Canada, Schengen, Singapore or UK visa)', fee: 0, feeNote: 'free', days: 0, buffer: 4, apply: 'eTravel registration online within 72 hours before the flight', url: 'https://etravel.gov.ph', docs: BASE, extras: ['eTravel QR for every traveller', 'Return ticket and hotel are checked at immigration'], tips: ['Visa-free entry for Indian tourists started in 2025; verify the rule a month before the batch'] },
  japan: { country: 'Japan', type: 'embassy', stay: '15 to 30 days', fee: 1500, feeNote: 'visa fee about ₹500 to ₹1,900 plus the VFS service fee', days: 7, buffer: 10, apply: 'VFS Japan or the e-visa portal through an accredited agency, 5 to 7 working days', url: 'https://www.evisa.mofa.go.jp', docs: BASE.concat(EMBASSY), extras: ['Day-by-day schedule in the Japanese format (we prepare it)'], tips: ['Bank statement with a healthy balance matters more than the letter'] },
  schengen: { country: 'Schengen', type: 'embassy', stay: '90 days in any 180', fee: 8500, feeNote: 'EUR 90 adult, EUR 45 for ages 6 to 12, free under 6, plus the VFS fee', days: 15, buffer: 25, apply: 'VFS of the country where you stay the longest; apply 15 days to 6 months before; biometrics in person', url: 'https://visa.vfsglobal.com', docs: BASE.concat(EMBASSY, ['Medical insurance of EUR 30,000 covering all Schengen states (mandatory)']), extras: ['Appointment slots fill 4 to 8 weeks ahead in season'], tips: ['Start 8 weeks out; a refused Schengen application loses the fee', 'Every document in English or with a certified translation'] },
  australia: { country: 'Australia', type: 'embassy', stay: 'up to 3 months', fee: 11000, feeNote: 'Visitor visa subclass 600, about AUD 200', days: 20, buffer: 20, apply: 'online through ImmiAccount, usually 2 to 5 weeks', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600', docs: BASE.concat(EMBASSY), extras: ['Biometrics at VFS after lodging'], tips: ['Lodge 6 weeks out; the department asks for more documents by email, answer within the deadline'] },
  uk: { country: 'United Kingdom', type: 'embassy', stay: 'up to 6 months', fee: 13500, feeNote: 'Standard Visitor visa about GBP 127', days: 15, buffer: 15, apply: 'online application, then biometrics at VFS; about 3 weeks', url: 'https://www.gov.uk/standard-visitor', docs: BASE.concat(EMBASSY), extras: [], tips: ['Priority service costs extra and still needs the biometrics slot'] },
  usa: { country: 'United States', type: 'embassy', stay: 'up to 6 months', fee: 15500, feeNote: 'B1/B2 visa USD 185', days: 30, buffer: 60, apply: 'DS-160 online, fee, then an interview appointment; waits can run to months', url: 'https://www.ustraveldocs.com/in', docs: BASE.concat(EMBASSY), extras: ['Interview at the consulate in person'], tips: ['Not realistic for a fixed-date group batch unless everyone already holds a visa'] },
  // Domestic permits for Indian citizens.
  ladakh: { country: 'India', region: 'Ladakh', type: 'permit', stay: 'as per permit', fee: 500, feeNote: 'environment and wildlife fee about ₹500 per person', days: 1, buffer: 2, apply: 'Inner Line Permit for Nubra, Pangong, Tso Moriri and Hanle, online or at the DC office in Leh, same day', url: 'https://lahdclehpermit.in', docs: ['Government photo ID (Aadhaar, voter ID or passport)', 'Vehicle details for the permit (we fill it)'], extras: ['Foreign nationals need a Protected Area Permit through a registered agent'], tips: ['Carry 6 photocopies of the permit; checkposts keep one each'] },
  sikkim: { country: 'India', region: 'Sikkim', type: 'permit', stay: 'as per permit', fee: 200, feeNote: 'about ₹200 per person plus the vehicle permit', days: 1, buffer: 2, apply: 'Protected Area Permit for Nathula, Tsomgo and North Sikkim through a registered operator, one day before', url: 'https://sikkimtourism.gov.in', docs: ['Government photo ID with 2 photocopies', 'Two passport photos per person'], extras: ['Nathula is closed to foreign nationals; North Sikkim needs a group of 2 or more'], tips: ['Nathula permits are not issued on Mondays and Tuesdays; plan the day'] },
  arunachal: { country: 'India', region: 'Arunachal Pradesh', type: 'permit', stay: '15 or 30 days', fee: 100, feeNote: '₹100 per person', days: 1, buffer: 3, apply: 'Inner Line Permit online, usually within a day', url: 'https://arunachalilp.com', docs: ['Government photo ID', 'Passport photo (digital)'], extras: ['Tawang route checkposts stamp the ILP; keep it accessible'], tips: ['Apply for the exact district list (Tawang, West Kameng); a missing district stops the vehicle'] },
  nagaland: { country: 'India', region: 'Nagaland', type: 'permit', stay: '30 days', fee: 150, feeNote: 'about ₹150 per person', days: 1, buffer: 3, apply: 'Inner Line Permit online', url: 'https://ilp.nagaland.gov.in', docs: ['Government photo ID', 'Passport photo (digital)'], extras: [], tips: ['Hornbill festival week: apply 2 weeks early, the portal slows down'] },
  mizoram: { country: 'India', region: 'Mizoram', type: 'permit', stay: '15 days', fee: 170, feeNote: 'about ₹170 per person', days: 1, buffer: 3, apply: 'Inner Line Permit online or at Lengpui airport on arrival', url: 'https://ilp.mizoram.gov.in', docs: ['Government photo ID', 'Passport photo'], extras: [], tips: [] },
  manipur: { country: 'India', region: 'Manipur', type: 'permit', stay: '15 days', fee: 100, feeNote: 'about ₹100 per person', days: 1, buffer: 3, apply: 'Inner Line Permit online', url: 'https://manipurilponline.mn.gov.in', docs: ['Government photo ID', 'Passport photo'], extras: [], tips: ['Check the news desk before the batch; the state closes entry during unrest'] },
  lakshadweep: { country: 'India', region: 'Lakshadweep', type: 'permit', stay: 'as per permit', fee: 300, feeNote: 'about ₹300 per person plus heritage fees', days: 10, buffer: 15, apply: 'Entry permit through the administration portal with a police clearance certificate, 10 to 15 working days', url: 'https://epermit.utl.gov.in', docs: ['Government photo ID', 'Police clearance certificate from your city', 'Three passport photos', 'Confirmed ship or flight ticket and resort booking'], extras: [], tips: ['The police certificate is the slow part; start 4 weeks out'] },
  andaman: { country: 'India', region: 'Andaman', type: 'none', stay: 'no limit', fee: 0, feeNote: 'no permit for Indian citizens', days: 0, buffer: 0, apply: 'nothing; carry a government photo ID', url: 'https://www.andamantourism.gov.in', docs: ['Government photo ID for every traveller (kids: school ID or birth certificate)'], extras: ['Foreign nationals get a free Restricted Area Permit on arrival at Port Blair, 30 days', 'Tribal reserves are closed to everyone'], tips: [] },
  chardham: { country: 'India', region: 'Uttarakhand Char Dham', type: 'permit', stay: 'as per registration', fee: 0, feeNote: 'free registration', days: 1, buffer: 7, apply: 'Yatra registration online for every pilgrim before travel', url: 'https://registrationandtouristcare.uk.gov.in', docs: ['Government photo ID', 'Mobile number for the OTP', 'Health declaration for travellers over 60'], extras: ['Daily caps apply; a batch without registration is turned back at the gate'], tips: ['Register the whole group the day bookings close'] },
  india: { country: 'India', type: 'none', stay: 'no limit', fee: 0, feeNote: 'no visa or permit', days: 0, buffer: 0, apply: 'nothing; carry a government photo ID', url: '', docs: ['Government photo ID for every traveller (Aadhaar, voter ID, driving licence or passport)', 'Kids: school ID or birth certificate', 'Original ID of every adult at hotel check-in'], extras: ['Foreign nationals: passport and visa, and a C-form at every hotel'], tips: [] },
};
const ALIASES = { dubai: 'uae', 'abu dhabi': 'uae', emirates: 'uae', bali: 'indonesia', jakarta: 'indonesia', phuket: 'thailand', bangkok: 'thailand', krabi: 'thailand', pattaya: 'thailand', 'kuala lumpur': 'malaysia', langkawi: 'malaysia', 'sri lanka': 'srilanka', colombo: 'srilanka', hanoi: 'vietnam', danang: 'vietnam', 'da nang': 'vietnam', 'ho chi minh': 'vietnam', male: 'maldives', kathmandu: 'nepal', pokhara: 'nepal', thimphu: 'bhutan', paro: 'bhutan', tbilisi: 'georgia', almaty: 'kazakhstan', baku: 'azerbaijan', yerevan: 'armenia', tashkent: 'uzbekistan', samarkand: 'uzbekistan', istanbul: 'turkey', cappadocia: 'turkey', cairo: 'egypt', muscat: 'oman', nairobi: 'kenya', masai: 'kenya', 'hong kong': 'hongkong', 'siem reap': 'cambodia', angkor: 'cambodia', manila: 'philippines', palawan: 'philippines', tokyo: 'japan', kyoto: 'japan', europe: 'schengen', paris: 'schengen', amsterdam: 'schengen', switzerland: 'schengen', italy: 'schengen', france: 'schengen', germany: 'schengen', spain: 'schengen', sydney: 'australia', melbourne: 'australia', london: 'uk', england: 'uk', britain: 'uk', america: 'usa', 'new york': 'usa', leh: 'ladakh', nubra: 'ladakh', pangong: 'ladakh', hanle: 'ladakh', gangtok: 'sikkim', nathula: 'sikkim', gurudongmar: 'sikkim', tawang: 'arunachal', ziro: 'arunachal', kohima: 'nagaland', hornbill: 'nagaland', aizawl: 'mizoram', imphal: 'manipur', agatti: 'lakshadweep', 'port blair': 'andaman', havelock: 'andaman', kedarnath: 'chardham', badrinath: 'chardham', gangotri: 'chardham', yamunotri: 'chardham' };
const TYPE_WORDS = { free: 'no visa needed', card: 'visa-free, with an online arrival card', voa: 'visa on arrival', evisa: 'e-visa before flying', eta: 'online travel authorisation', embassy: 'visa through the embassy or visa centre', conditional: 'e-visa only with another valid visa, otherwise an embassy visa', none: 'no visa or permit', permit: 'permit needed' };
const money = (n) => '₹' + Math.round(+n || 0).toLocaleString('en-IN');
const fmtDate = (d) => new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
const DAY = 86400e3;
const STATUSES = ['not_started', 'documents', 'applied', 'approved', 'rejected', 'not_needed'];

function mentionsVisa(text) { return /\b(visa|e-?visa|voa|visa on arrival|visa[- ]free|passport|ilp|inner line|protected area|permit|sdf|eta|arrival card|tdac|mdac|imuga|documents? (for|needed|required|chahiye|lagenge)|kya documents|paperwork|immigration)\b/i.test(String(text || '')); }

class VisaDesk {
  constructor(brain, { dataDir } = {}) {
    this.brain = brain; this.file = path.join(dataDir || (brain && brain.dataDir) || '.', 'visa.json');
    this.state = { cases: [], checked: {} };
    try { if (fs.existsSync(this.file)) Object.assign(this.state, JSON.parse(fs.readFileSync(this.file, 'utf8'))); } catch { /* fresh */ }
  }
  save() { try { fs.mkdirSync(path.dirname(this.file), { recursive: true }); const tmp = this.file + '.tmp'; fs.writeFileSync(tmp, JSON.stringify(this.state, null, 1)); fs.renameSync(tmp, this.file); } catch { /* read-only */ } }

  /** Rule for a destination name, country, city or alias; null when unknown. */
  rule(name) {
    const q = String(name || '').toLowerCase().trim(); if (!q) return null;
    const key = (k) => Object.assign({ key: k, checked: CHECKED }, KB[k]);
    if (KB[q]) return key(q);
    for (const [a, k] of Object.entries(ALIASES)) if (new RegExp('(^|[^a-z])' + a + '(?![a-z])').test(q)) return key(k);
    for (const [k, v] of Object.entries(KB)) if (new RegExp('(^|[^a-z])' + v.country.toLowerCase() + '(?![a-z])').test(q) && v.country !== 'India') return key(k);
    for (const k of Object.keys(KB)) if (new RegExp('(^|[^a-z])' + k + '(?![a-z])').test(q)) return key(k);
    const d = DEST.find(q); if (d) { if (d.country && d.country !== 'India') { const byCountry = Object.keys(KB).find(k => KB[k].country.toLowerCase() === d.country.toLowerCase()); if (byCountry) return key(byCountry); } const dn = d.name.toLowerCase(); for (const [a, k] of Object.entries(ALIASES)) if (dn.includes(a)) return key(k); return key('india'); }
    return null;
  }
  /** Everything a traveller must do, and by when, for a trip on a date. */
  timeline(rule, tripDate) {
    if (!rule || !tripDate) return null; const dep = new Date(tripDate); const lead = (rule.days || 0) + (rule.buffer || 0);
    const applyBy = new Date(dep.getTime() - lead * DAY); const daysLeft = Math.ceil((applyBy - Date.now()) / DAY);
    return { applyBy: applyBy.toISOString().slice(0, 10), leadDays: lead, daysLeft, status: lead === 0 ? 'nothing to apply' : daysLeft < 0 ? 'late' : daysLeft <= 3 ? 'now' : 'later' };
  }
  needsAction(rule) { return !!rule && !['free', 'none'].includes(rule.type); }
  /** Customer-facing brief, grounded on the rule and the batch date. */
  brief(rule, { tripDate, name, hi, group, assistFee } = {}) {
    if (!rule) return hi ? 'Batao kaunsa country, main visa ka poora rule bhej deta hoon.' : 'Tell me the country and I will send the exact visa rule.';
    const tl = this.timeline(rule, tripDate); const place = rule.region || rule.country; const n = group > 1 ? group : 1;
    const fee = rule.fee ? `${money(rule.fee)} per person (${rule.feeNote})` : rule.feeNote;
    const far = tl && tl.daysLeft > 365; const by = tl && tl.leadDays ? (hi ? ` ${fmtDate(tl.applyBy)} tak apply karna hai${far ? '' : ` (${tl.status === 'late' ? 'ab urgent route' : tl.daysLeft + ' din bache hain'})`}.` : ` Apply by ${fmtDate(tl.applyBy)}${far ? '' : ` (${tl.status === 'late' ? 'we are past it: urgent route' : tl.daysLeft + ' days left'})`}.`) : '';
    const docs = rule.docs.slice(0, 4).join('; ');
    const help = assistFee > 0 ? (hi ? `Hum poore group ka ek saath karte hain, handling ${money(assistFee)} per person, visa fee actual.` : `We do the whole group together; handling ${money(assistFee)} per person, visa fee at actuals.`) : (hi ? 'Hum poore group ka ek saath karte hain, koi handling charge nahi, visa fee actual.' : 'We do the whole group together at no handling charge; the visa fee is at actuals.');
    if (['free', 'none'].includes(rule.type)) return hi ? `${place} ke liye visa nahi lagta. Saath rakho: ${docs}.${rule.tips[0] ? ' ' + rule.tips[0] + '.' : ''}` : `${place}: ${TYPE_WORDS[rule.type]} for Indian passports. Carry: ${docs}.${rule.tips[0] ? ' ' + rule.tips[0] + '.' : ''}`;
    if (rule.type === 'card' || rule.type === 'eta') return hi ? `${place}: Indian passport ke liye ${rule.type === 'card' ? 'visa-free' : 'online authorisation'}, ${rule.stay}. ${rule.apply} (${rule.url}). Fee: ${fee}.${by} Saath rakho: ${docs}. Hum form bhar dete hain, bas passport ka photo bhejo.` : `${place}: ${TYPE_WORDS[rule.type]} for Indian passports, stay ${rule.stay}. ${rule.apply} (${rule.url}). Fee: ${fee}.${by} Carry: ${docs}. We fill the form for you; just send a photo of the passport page.`;
    if (rule.type === 'voa') return hi ? `${place}: visa on arrival, ${rule.stay}, fee ${fee}. ${rule.apply} (${rule.url}).${by} Saath rakho: ${docs}. ${help}` : `${place}: visa on arrival, stay ${rule.stay}, fee ${fee}. ${rule.apply} (${rule.url}).${by} Carry: ${docs}. ${help}`;
    if (rule.type === 'permit') return hi ? `${place}: ${rule.apply}; fee ${fee}.${by} Chahiye: ${docs}. Permit hum banwate hain, ID ki copy bhej do.` : `${place}: ${rule.apply}; fee ${fee}.${by} Needed: ${docs}. We arrange the permit; send an ID copy for each traveller.`;
    // evisa, embassy, conditional
    return hi ? `${place}: ${TYPE_WORDS[rule.type]}. ${rule.apply}; fee ${fee}; stay ${rule.stay}.${by} Documents: ${docs}. ${help}${rule.tips[0] ? ' Dhyan: ' + rule.tips[0] + '.' : ''}` : `${place}: ${TYPE_WORDS[rule.type]}. ${rule.apply}; fee ${fee}; stay ${rule.stay}.${by} Documents for ${n > 1 ? 'each of the ' + n : 'you'}: ${docs}. ${help}${rule.tips[0] ? ' Watch out: ' + rule.tips[0] + '.' : ''}`;
  }
  /** Chief-facing card: everything about one destination. */
  card(name) {
    const r = this.rule(name); if (!r) return `No visa rule for "${name}" in the desk yet; tell me the country and I will add it.`;
    const place = r.region || r.country;
    return [`${place}: ${TYPE_WORDS[r.type]} (Indian passport). Stay: ${r.stay}. Fee: ${r.fee ? money(r.fee) + ' per person, ' + r.feeNote : r.feeNote}. Processing: ${r.days ? r.days + ' working days' : 'none'}; we keep ${r.buffer} extra days.`, `Apply: ${r.apply}${r.url ? ' · ' + r.url : ''}.`, `Documents: ${r.docs.join('; ')}.`, r.extras.length ? `Also: ${r.extras.join('; ')}.` : '', r.tips.length ? `Traps: ${r.tips.join('; ')}.` : '', `Checked ${r.checked}; verify on the official link before each batch.`].filter(Boolean).join('\n');
  }

  // ---- cases ----
  openCase({ lead, name, trip, country, seats = 1 }) {
    const key = `${lead}|${trip}`; let c = this.state.cases.find(x => x.key === key);
    if (!c) { c = { id: Date.now().toString(36) + Math.random().toString(36).slice(2, 5), key, lead, name: name || lead, trip, country, seats, status: 'not_started', docs: {}, notes: '', created: Date.now(), updated: Date.now() }; this.state.cases.unshift(c); }
    else Object.assign(c, { name: name || c.name, country: country || c.country, seats: seats || c.seats, updated: Date.now() });
    this.save(); return c;
  }
  update(id, patch) {
    const c = this.state.cases.find(x => x.id === id); if (!c) return null;
    if (patch.status && STATUSES.includes(patch.status)) { c.status = patch.status; if (patch.status === 'applied') c.appliedAt = c.appliedAt || Date.now(); if (['approved', 'rejected'].includes(patch.status)) c.decidedAt = Date.now(); }
    if (patch.doc) c.docs[patch.doc] = patch.done !== false; if (patch.docs && typeof patch.docs === 'object') Object.assign(c.docs, patch.docs);
    for (const k of ['notes', 'appointment', 'passport', 'seats', 'name']) if (patch[k] != null) c[k] = patch[k];
    c.updated = Date.now(); this.save(); return c;
  }
  cases(filter = {}) { return this.state.cases.filter(c => (!filter.trip || c.trip === filter.trip) && (!filter.lead || c.lead === filter.lead) && (!filter.status || c.status === filter.status)); }
  /** Make sure every booked traveller on a trip that needs a visa or permit has a case; returns the per-trip picture. */
  sync(growth) {
    const out = []; if (!growth) return out;
    for (const t of growth.upcoming(8)) {
      const rule = this.rule(t.name); if (!rule || !this.needsAction(rule)) continue;
      const booked = growth.state.leads.filter(l => l.trip && l.trip.toLowerCase() === t.name.toLowerCase() && ['advance', 'balance', 'hold'].includes(l.stage));
      for (const l of booked) this.openCase({ lead: l.id, name: l.name || l.id, trip: t.name, country: rule.region || rule.country, seats: l.seats || 1 });
      const cs = this.cases({ trip: t.name }); const tl = this.timeline(rule, t.date);
      const byStatus = {}; for (const c of cs) byStatus[c.status] = (byStatus[c.status] || 0) + 1;
      const pending = cs.filter(c => !['approved', 'not_needed'].includes(c.status));
      out.push({ trip: t.name, date: t.date, country: rule.region || rule.country, type: rule.type, typeText: TYPE_WORDS[rule.type], applyBy: tl ? tl.applyBy : null, daysLeft: tl ? tl.daysLeft : null, urgency: tl ? tl.status : 'later', cases: cs.length, byStatus, pending: pending.map(c => ({ id: c.id, lead: c.lead, name: c.name, status: c.status, seats: c.seats })), url: rule.url, apply: rule.apply, fee: rule.fee, feeNote: rule.feeNote, docs: rule.docs });
    }
    return out;
  }
  /** Flags for the trip board. */
  flags(growth) { const f = {}; for (const s of this.sync(growth)) if (s.pending.length) f[s.trip] = `${s.country}: ${s.pending.length} traveller${s.pending.length > 1 ? 's' : ''} without ${s.type === 'permit' ? 'permit' : 'visa'} ${s.applyBy ? `(${s.urgency === 'late' ? 'past the apply-by date ' + fmtDate(s.applyBy) + ', urgent route' : 'apply by ' + fmtDate(s.applyBy)})` : ''}`; return f; }
  summary() { const c = this.state.cases; const by = {}; for (const x of c) by[x.status] = (by[x.status] || 0) + 1; return { cases: c.length, byStatus: by, countries: Object.keys(KB).length, checked: CHECKED }; }
}

module.exports = { VisaDesk, KB, ALIASES, TYPE_WORDS, STATUSES, mentionsVisa, CHECKED };
